// src/lib/default-data.ts — Fallback data when database is unavailable
//
// This file contains hardcoded default channels and categories from the
// genztv-backup-2026-07-14.json export. When the Neon database is down
// (connection failure, adapter error, etc.), the API routes fall back
// to this data so the app still works without a database.
//
// Generated from: genztv-backup-2026-07-14.json (61 active channels)

export interface DefaultChannel {
  id: string
  name: string
  logo: string
  category: string
  streamType: string
  streamUrl: string
  githubM3uPath: string
  language: string
  country: string
  tags: string
  isFeatured: boolean
  isActive: boolean
  viewCount: number
  sourcePageUrl: string
  refreshPattern: string
  autoRefresh: boolean
  refreshError: string
}

export interface DefaultCategory {
  id: string
  name: string
  icon: string
  color: string
  order: number
  channelCount: number
}

export const DEFAULT_CHANNELS: DefaultChannel[] = [
  {
    "id": "cmqt3z89k0664o40akj8xb7dl",
    "name": "Caze TV",
    "logo": "https://upload.wikimedia.org/wikipedia/en/thumb/6/64/Caz%C3%A9TV_logo.svg/1280px-Caz%C3%A9TV_logo.svg.png",
    "category": "sports",
    "streamType": "m3u8",
    "streamUrl": "https://dfr80qz435crc.cloudfront.net/MNOP/Amagi/Caze/Caze_TV_BR/1080p-vtt/index.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 1712,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqt3z8dz0666o40awco26bpu",
    "name": "beIN Sports 1",
    "logo": "https://www.beinsports.com/_next/static/media/bein_logo.af017869.webp",
    "category": "sports,football",
    "streamType": "m3u8_proxy",
    "streamUrl": "https://1nyaler.streamhostingcdn.top/stream/23/index.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": true,
    "isActive": true,
    "viewCount": 7613,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqt3z8pn066co40ay0b3cjm2",
    "name": "WIN Sports",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Win_Sports_nuevo_logo.svg/1280px-Win_Sports_nuevo_logo.svg.png",
    "category": "sports",
    "streamType": "m3u8",
    "streamUrl": "https://1nyaler.streamhostingcdn.top/stream/32/index.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": true,
    "isActive": true,
    "viewCount": 2039,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqt3z8s1066eo40ahkjan937",
    "name": "Willow Sports 2",
    "logo": "https://assets.goal.com/images/v3/blt4aeb827b3c526988/Willow-Sports%20logo.jpg",
    "category": "sports,cricket",
    "streamType": "m3u8_direct",
    "streamUrl": "https://lb12.strmd.st/secure/QNqmJPpaDSfgNqWZYyRFOlNyacwXyKYK/rtmp/stream/streamed-willow2_720/1/high/mono.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": true,
    "isActive": true,
    "viewCount": 586,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqt3z8xs066io40azplnrrmw",
    "name": "TNT Sports 1",
    "logo": "https://cdn.comedy.co.uk/images/channels/tnt_sports_1.jpg",
    "category": "entertainment",
    "streamType": "iframe",
    "streamUrl": "https://playeraio.top/embed2.php?id=btsp1",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 494,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqt3z96h066oo40at4xagtz0",
    "name": "Sony Sports Ten 1",
    "logo": "https://jiotvimages.cdn.jio.com/dare_images/shows/epgdata/1db079b3d4a32e9257208fafdfcd0e68.png",
    "category": "entertainment",
    "streamType": "iframe",
    "streamUrl": "https://playerado.top/embed2.php?id=ten1",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 593,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqt3z9kg066yo40ae57ebxer",
    "name": "T Sports HD",
    "logo": "https://www.circle-sports.com/assets/images/T%20Sports1738680543.png",
    "category": "sports",
    "streamType": "mpegts",
    "streamUrl": "http://rgkkw.live/live/1Aoen7elp5/IgMJ60tmAa/130714.ts",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 657,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqt3z9n90670o40al4hrd6zh",
    "name": "Fox Sports Cricket",
    "logo": "https://upload.wikimedia.org/wikipedia/en/f/f4/Fox_Cricket_Logo.png",
    "category": "sports,cricket",
    "streamType": "iframe",
    "streamUrl": "https://playerado.top/embed2.php?id=fox501",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 561,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqt3z9ta0674o40a7vp31lzj",
    "name": "Willow Extra",
    "logo": "https://bobgoldpr.com/wp-content/uploads/2025/01/WILLOW_2023_Primary-Stacked.png",
    "category": "entertainment",
    "streamType": "iframe",
    "streamUrl": "https://playerado.top/embed2.php?id=willowextra",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 135,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqt3z9vx0676o40a7ixt0nf6",
    "name": "FOX Sports 1080p",
    "logo": "https://images.seeklogo.com/logo-png/31/2/fs1-logo-png_seeklogo-314481.png",
    "category": "entertainment",
    "streamType": "m3u8",
    "streamUrl": "https://d1jzu95oc8fgt3.cloudfront.net/FOX_Sports.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 987,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqt3z9yo0678o40a64itzx88",
    "name": "FS 1 - FIFA",
    "logo": "https://images.seeklogo.com/logo-png/31/2/fs1-logo-png_seeklogo-314481.png",
    "category": "sports,football",
    "streamType": "m3u8",
    "streamUrl": "https://andro.226503.xyz/checklist/androstreamliveexn2.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 402,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqt3zaa4067go40an4dw7jtf",
    "name": "beIN Sports 3",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/c/c4/Logo_bein_sports_3.png",
    "category": "sports",
    "streamType": "m3u8",
    "streamUrl": "https://andro.226503.xyz/checklist/androstreamlivebs3.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": true,
    "isActive": true,
    "viewCount": 2013,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqt5i34p06bso40aqjb3pihh",
    "name": "CAZE TV 720p",
    "logo": "",
    "category": "entertainment",
    "streamType": "m3u",
    "streamUrl": "https://dfr80qz435crc.cloudfront.net/MNOP/Amagi/Caze/Caze_TV_BR/720p-vtt/index.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 239,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqtl86qy00fyqr0ak5om7bm4",
    "name": "2TV Sport 🇳🇴",
    "logo": "",
    "category": "entertainment",
    "streamType": "m3u8",
    "streamUrl": "https://tv.cdn.xsg.ge/gpb-2tv/index.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 125,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqtl86tb00g0qr0aeield1jn",
    "name": "BEIN SPORT EXTRA Ñ  (1080p)",
    "logo": "https://metallife.com/wp-content/uploads/2021/09/bein_sports_logos.jpg",
    "category": "sports",
    "streamType": "m3u8",
    "streamUrl": "https://bein-esp-xumo.amagi.tv/playlistR1080p.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 224,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqtl86w600g2qr0ae8ijzs9s",
    "name": "BEIN SPORT EXTRA Ñ  (720p)",
    "logo": "https://hubdeportivo.com/wp-content/uploads/2022/09/Bein-Sports-Xtra.png",
    "category": "sports,football",
    "streamType": "m3u8",
    "streamUrl": "https://bein-esp-xumo.amagi.tv/playlistR720P.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": true,
    "isActive": true,
    "viewCount": 1267,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqtl872800g6qr0a0i534fta",
    "name": "FOX NY",
    "logo": "",
    "category": "entertainment",
    "streamType": "m3u8",
    "streamUrl": "https://cdn-uw2-prod.tsv2.amagi.tv/linear/amg00488-foxdigital-wnyw-lgus/playlist.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 157,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqtl87xa00ggqr0awqj2qd2j",
    "name": "REAL MADRID TV",
    "logo": "https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg",
    "category": "football",
    "streamType": "m3u8",
    "streamUrl": "https://rmtv.akamaized.net/hls/live/2043153/rmtv-es-web/bitrate_3.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 178,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqtl882i00giqr0a4tk0fc11",
    "name": "SKY SPORT LALIGA 🇲🇽",
    "logo": "",
    "category": "entertainment",
    "streamType": "m3u8",
    "streamUrl": "http://179.60.224.196:8000/play/a0i7/index.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 112,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqtl88jw00guqr0acrvlkmrn",
    "name": "BEIN SPORTS 5 HD",
    "logo": "https://r2.thesportsdb.com/images/media/channel/logo/BeIn_Sports_5_US.png",
    "category": "sports,football",
    "streamType": "m3u",
    "streamUrl": "https://node8.no-612.workers.dev/resource/MjQwNTk5MDY0MTY5OjI0MDU5OTA2NDE2OToxMjAzNTpsaXZl/index",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": true,
    "isActive": true,
    "viewCount": 850,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqtl88s700h0qr0aifxy6ijt",
    "name": "beIN Sports 2",
    "logo": "",
    "category": "sports",
    "streamType": "m3u",
    "streamUrl": "https://1nyaler.streamhostingcdn.top/stream/21/index.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 139,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqtl88uy00h2qr0ayjfjak01",
    "name": "BEIN Sports  1080p",
    "logo": "https://mma.prnewswire.com/media/1610428/beIN_SPORTS_Logo.jpg?p=facebook",
    "category": "sports,football",
    "streamType": "m3u8",
    "streamUrl": "https://andro.226503.xyz/checklist/androstreamlivebs1.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 464,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqtl88xt00h4qr0aacpf4dki",
    "name": "WDSC",
    "logo": "https://worlddownhillskateboardingchampionship.com/wp-content/uploads/2021/02/WDSC-logo4-2.png",
    "category": "entertainment",
    "streamType": "m3u8",
    "streamUrl": "https://d9ssxzmclhfo4.cloudfront.net/bein_sports720p.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 113,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqtl894600h8qr0ame4kk0k3",
    "name": "FIGHT NETWORK",
    "logo": "",
    "category": "entertainment",
    "streamType": "m3u8",
    "streamUrl": "https://amg00966-amg00966c10-amgplt0201.playout.now3.amagi.tv/playlist/amg00966-amg00966c10-amgplt0201/playlist.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 109,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqtl898u00haqr0a9c7k6ozy",
    "name": "FOX Sports (720)",
    "logo": "https://tv.jsssbd.com/assets/logos/up_34b55a9f25b6.png",
    "category": "entertainment",
    "streamType": "m3u8",
    "streamUrl": "https://d1jzu95oc8fgt3.cloudfront.net/FOX_Sports720p.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 279,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqtl89bm00hcqr0aakay5axc",
    "name": "GoPro",
    "logo": "",
    "category": "entertainment",
    "streamType": "m3u8",
    "streamUrl": "https://3a1b4d927c02473b806350cc162d271f.mediatailor.us-west-2.amazonaws.com/v1/master/ba62fe743df0fe93366eba3a257d792884136c7f/LINEAR-891-GOPRO-FREELIVESPORTS/mt/freelivesports/891/hls/master/playlist.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 185,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqtl89du00heqr0a0rlspcy1",
    "name": "Redbull TV",
    "logo": "",
    "category": "entertainment",
    "streamType": "m3u8",
    "streamUrl": "https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master_3360.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 108,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqtnf32600u6qr0aqse7lyah",
    "name": "BEIN SPORTS 3 France ",
    "logo": "https://yt3.googleusercontent.com/ytc/AIdro_l6ubcgcA94MLXY28XrHLzdOCLmpSebx0JNk4XBMCI-SVE=s900-c-k-c0x00ffffff-no-rj",
    "category": "sports",
    "streamType": "mpegts",
    "streamUrl": "http://145.239.5.177/559/mpeg.ts",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 419,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqtwl9b9002ioi1vugwk7cyr",
    "name": "Now TV 4K - FIFA",
    "logo": "https://i.ibb.co/C32Rhtff/1000284518.png",
    "category": "FIFA,sports,football",
    "streamType": "mpegts",
    "streamUrl": "http://starhub.pro/live/farhat-3379/67897-913379/745270.ts",
    "githubM3uPath": "",
    "language": "en",
    "country": "int",
    "tags": "",
    "isFeatured": true,
    "isActive": true,
    "viewCount": 4395,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqtwl9gt002moi1v71434jzl",
    "name": "beIN Sports Max 2",
    "logo": "https://tv.jsssbd.com/assets/logos/up_dd5b6025d6e3.png",
    "category": "FIFA,sports,football",
    "streamType": "m3u8_direct",
    "streamUrl": "https://edge22.776740.ir.cdn.ir/hls2/sport.m3u8",
    "githubM3uPath": "",
    "language": "en",
    "country": "int",
    "tags": "",
    "isFeatured": true,
    "isActive": true,
    "viewCount": 1096,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqtwl9jh002ooi1v3fu3my4g",
    "name": "D Sports",
    "logo": "https://tv.jsssbd.com/assets/logos/up_e4eadd52194d.png",
    "category": "Sports",
    "streamType": "m3u",
    "streamUrl": "https://1nyaler.streamhostingcdn.top/stream/106/index.m3u8",
    "githubM3uPath": "",
    "language": "en",
    "country": "int",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 711,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqtwl9m7002qoi1vohzcnweg",
    "name": "SuperSport",
    "logo": "https://tv.jsssbd.com/assets/logos/up_3da1324fc154.png",
    "category": "FIFA,sports",
    "streamType": "mpegts",
    "streamUrl": "https://cdn.jsssbd.com/api/ts.php?u=http://rgkkw.live/live/1Aoen7elp5/IgMJ60tmAa/745149.ts",
    "githubM3uPath": "",
    "language": "en",
    "country": "int",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 848,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqtwl9sh002uoi1vl8hyvsmy",
    "name": "Willow Sports",
    "logo": "https://tv.jsssbd.com/assets/logos/up_d5b785798340.webp",
    "category": "Sports",
    "streamType": "m3u8_direct",
    "streamUrl": "https://warm-caverns-48629-92fab798385f.herokuapp.com/https://d36r8jifhgsk5j.cloudfront.net/Willow_TV540p.m3u8",
    "githubM3uPath": "",
    "language": "en",
    "country": "int",
    "tags": "",
    "isFeatured": true,
    "isActive": true,
    "viewCount": 744,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqtwl9uy002woi1vlhesjtfl",
    "name": "Telemundo",
    "logo": "https://tv.jsssbd.com/assets/logos/up_d2a970acedeb.png",
    "category": "FIFA,sports",
    "streamType": "m3u8_direct",
    "streamUrl": "https://nbculocallive.akamaized.net/hls/live/2037499/puertorico/stream1/master_720.m3u8",
    "githubM3uPath": "",
    "language": "en",
    "country": "int",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 280,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqtwl9xi002yoi1v33x0wdfl",
    "name": "Cricket Gold",
    "logo": "https://tv.jsssbd.com/assets/logos/up_d1989345c24f.png",
    "category": "Cricket",
    "streamType": "m3u8_direct",
    "streamUrl": "https://streams2.sofast.tv/ptnr-yupptv/title-cricketgold/v1/master/611d79b11b77e2f571934fd80ca1413453772ac7/b2048bb8-1686-4432-aa50-647245383e0c/manifest.m3u8",
    "githubM3uPath": "",
    "language": "en",
    "country": "int",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 216,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqtwl9zv0030oi1v9441go2f",
    "name": "Sport.tv 1",
    "logo": "https://tv.jsssbd.com/assets/logos/up_69fb4e7e4a0a.png",
    "category": "Sports",
    "streamType": "m3u8_direct",
    "streamUrl": "https://1nyaler.streamhostingcdn.top/stream/33/index.m3u8",
    "githubM3uPath": "",
    "language": "en",
    "country": "int",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 242,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqtwla4i0034oi1vlij1fv53",
    "name": "Sky Sports Cricket",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Sky_Sports_Cricket_-_Logo_2025.svg/3840px-Sky_Sports_Cricket_-_Logo_2025.svg.png",
    "category": "Sports",
    "streamType": "m3u8_direct",
    "streamUrl": "https://cdn.jsssbd.com/api/hls.php?u=https%3A%2F%2Fbl.rutube.ru%2Flivestream%2F7c13a51576b9ff2601f08f5d57dd5169%2Findex.m3u8%3Fs%3D8Q-Mt7GTaRI2Eo9LNZ9mrg%26e%3D2081082141",
    "githubM3uPath": "",
    "language": "en",
    "country": "int",
    "tags": "",
    "isFeatured": true,
    "isActive": true,
    "viewCount": 360,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqtwlafj003coi1v0relf58d",
    "name": "FoX Sports",
    "logo": "https://tv.jsssbd.com/assets/logos/up_34b55a9f25b6.png",
    "category": "FIFA",
    "streamType": "m3u8_direct",
    "streamUrl": "https://cdn.jsssbd.com/api/hls.php?u=https://d1jzu95oc8fgt3.cloudfront.net/FOX_Sports1080p.m3u8",
    "githubM3uPath": "",
    "language": "en",
    "country": "int",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 421,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqtwlai9003eoi1v0dopzjpv",
    "name": "DD Sports",
    "logo": "https://tv.jsssbd.com/assets/logos/up_c2cffd774183.jpg",
    "category": "Cricket",
    "streamType": "m3u8_proxy",
    "streamUrl": "https://d3qs3d2rkhfqrt.cloudfront.net/out/v1/b17adfe543354fdd8d189b110617cddd/index_7.m3u8",
    "githubM3uPath": "",
    "language": "en",
    "country": "int",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 356,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqwrifbf0h55ns1vzl1xutgf",
    "name": "beIN Sports 1 Max ",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/5/50/Logo_bein_sports_max_1.png",
    "category": "sports,football",
    "streamType": "m3u8_direct",
    "streamUrl": "http://starhub.pro/live/farhat-3379/67897-913379/744523.ts",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": true,
    "isActive": true,
    "viewCount": 884,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqwrlf0j0h5sns1vx5xq8to8",
    "name": "CCTV 5",
    "logo": "https://i.namu.wiki/i/kkvLXQ4GxUGx9W3l-MPM9AlBY9eMN0Rk5ILOPorodRkJzyL-OPe1BbIKDH2Nvr29bV0grWlBBKHXi6HySdBzFQ.svg",
    "category": "sports",
    "streamType": "m3u",
    "streamUrl": "https://play1.gzxdby.com/live/783234345958_4547667094.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 207,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqwsg22r0hdcns1v8itylqin",
    "name": "Bein Sport Arabic",
    "logo": "https://a57.foxsports.com/statics.foxsports.com/www.foxsports.com/content/uploads/2023/05/1280/1280/IMG_6227.png?ve=1&tl=1",
    "category": "Other",
    "streamType": "m3u8",
    "streamUrl": "https://cp11.adabmedia.com/hls2/sport.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 503,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqwsg29h0hdgns1v42szsz28",
    "name": "SOMOY TV HD",
    "logo": "https://i.imgur.com/i54AQic.png",
    "category": "Sports",
    "streamType": "m3u8_direct",
    "streamUrl": "https://live.thebosstv.com:30443/dwlive/Somoy-TV/chunks.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": true,
    "isActive": true,
    "viewCount": 6758,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqwsg2jz0hdmns1vk5w8qfa0",
    "name": "Win Sports",
    "logo": "https://diem369.com/cdn/shop/files/win-sports-1698354.png",
    "category": "Sports",
    "streamType": "m3u8",
    "streamUrl": "https://1nyaler.streamhostingcdn.top/stream/32/index.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 128,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqwsg2si0hdsns1vtmixgihr",
    "name": "D Sports 2",
    "logo": "https://cdn.mos.cms.futurecdn.net/kHeXzAT9cKJ8CiqmRsxEkk.jpg",
    "category": "Sports",
    "streamType": "m3u8",
    "streamUrl": "https://m.mxonlive.xyz/nexusstream/ch08.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 269,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqwsg2xn0hdwns1vfmo8i4a3",
    "name": "FUSSBALL TV",
    "logo": "https://a57.foxsports.com/statics.foxsports.com/www.foxsports.com/content/uploads/2023/05/1280/1280/IMG_6227.png?ve=1&tl=1",
    "category": "Sports",
    "streamType": "m3u8",
    "streamUrl": "https://edge22.776740.ir.cdn.ir/hls2/rasf1.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": true,
    "isActive": true,
    "viewCount": 1268,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqwsg3ko0hecns1v8awxlgq4",
    "name": "CazéTV FIFA (1080P)",
    "logo": "https://images.seeklogo.com/logo-png/61/1/cazetv-logo-png_seeklogo-619708.png",
    "category": "Sports",
    "streamType": "m3u8",
    "streamUrl": "https://dfr80qz435crc.cloudfront.net/MNOP/Amagi/Caze/Caze_TV_BR/1080p-vtt/index.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": true,
    "isActive": true,
    "viewCount": 1881,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqwsg3u20heins1vpq2hlnuy",
    "name": "DIRECT TV FHD",
    "logo": "https://cdn.mos.cms.futurecdn.net/kHeXzAT9cKJ8CiqmRsxEkk.jpg",
    "category": "Sports,football",
    "streamType": "m3u8_direct",
    "streamUrl": "https://proxymarket.shop/api/public/hls?url=https%3A%2F%2Fandro.226503.xyz%2Fchecklist%2Fandrostreamlivebs1.m3u8%3Fref%3Dfifa",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": true,
    "isActive": true,
    "viewCount": 958,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqwsg44i0heons1vp7tusxnt",
    "name": "Fox Sports HD",
    "logo": "https://upload.wikimedia.org/wikipedia/commons/e/e5/Fox_Sports_Netherlands_Logo.png",
    "category": "Sports",
    "streamType": "m3u",
    "streamUrl": "https://amg00488-foxdigital-wnyw-lgus-qxl2g.amagi.tv/ts-us-w2-n2/playlist/amg00488-foxdigital-wnyw-lgus/cb543d1f7f6c648d9ad43e60d8ef46a2f9591fde1d6988693eb5518975d1073edce2a59caa08ff16388f1ede7f0a66413a3e951fda77118fd87eb141453c5728cfffe729a2c05616b7db083429b56a062a866a68ac39437ed0e21f48a238b6720a5aa82a66443d80b846ac725bdb80148b61299bce8c37683f03409a5e5afba358b1ebb30f4dde39a9b41455922d43e59f43c8821da689d0089c5e8627a7109c93a68fd641d386f31d93738aa19d71581fbba43bf9eb5cb8dd96683d99622034713f8482a08e85b81b253938d9ecc2be1f9f59aedb64e9c856ca52ad1fcef9593c8a70b50ba0243f4ce9620b5385d752606884eda181fa0ffedc0cf48fe6c77a7095f75b2d09992d9015223694f2dc07c4ed21d6e773cbe4325d0fc99f13cfc6f29bb9e4c40abd35dacbf1af3840656a104dd30ef5d43e8d69955380fa3e0d100d48a4915084a1dc5d3b6d06c6a356c61c16bc94dad786406b8430550aa853d85d047ec57b392fb263aacc4e19e34c3d8c3b39f44f26c013acca4bdb939bb45675e5a484289948e0ba0ddef378d94e344b0dbef76c12057b74deea691a233ba461e1c0c1f578190a8da22d9f0ce4d8b55fa3e102e236c614ae995eba8c13fbca09/5/1920x1080_5701132/index.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 301,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqwsg47m0heqns1vdqrifwuv",
    "name": "CCTV-4K (1080p)",
    "logo": "https://i.imgur.com/fxusYlX.png",
    "category": "General",
    "streamType": "m3u8",
    "streamUrl": "http://198.204.240.250:82/live/cctv4k.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 310,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqwsg4aw0hesns1vecb6uann",
    "name": "CCTV-1 (1080p)",
    "logo": "https://i.imgur.com/TpA3cUl.png",
    "category": "General",
    "streamType": "m3u8",
    "streamUrl": "http://69.30.245.50/live/cctv1.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 158,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqwsg4ec0heuns1v9niv2ruu",
    "name": "Willow HD TV",
    "logo": "https://s3.aynaott.com/storage/94a778ec3219f7eb54bdf1ee07a95788",
    "category": "Sports",
    "streamType": "m3u8",
    "streamUrl": "https://warm-caverns-48629-92fab798385f.herokuapp.com/https://d36r8jifhgsk5j.cloudfront.net/Willow_TV540p.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 192,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqwsg4rx0hf2ns1va2tfqqlw",
    "name": "UNITE 1 HD",
    "logo": "https://a57.foxsports.com/statics.foxsports.com/www.foxsports.com/content/uploads/2023/05/1280/1280/IMG_6227.png?ve=1&tl=1",
    "category": "Bangla,sports",
    "streamType": "mpegts",
    "streamUrl": "http://starhub.pro/live/farhat-3379/67897-913379/741567.ts",
    "githubM3uPath": "",
    "language": "HINDI",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 219,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqzizjnl01thmk1wlv4vsrnz",
    "name": "FIFA 2026",
    "logo": "https://ssl.gstatic.com/onebox/media/sports/logos/optimized/zRSSLZa7bC9pfCYAf7-DxA_64x64.png",
    "category": "sports",
    "streamType": "m3u8_direct",
    "streamUrl": "https://andro.evrenesoglu57.click/checklist/androstreamliveexn3.m3u8",
    "githubM3uPath": "",
    "language": "multi",
    "country": "int",
    "tags": "",
    "isFeatured": true,
    "isActive": true,
    "viewCount": 5392,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqzj095e01wkmk1wdaiq7vuq",
    "name": "FIFA 8K",
    "logo": "https://upload.wikimedia.org/wikipedia/en/thumb/1/17/2026_FIFA_World_Cup_emblem.svg/960px-2026_FIFA_World_Cup_emblem.svg.png",
    "category": "sports",
    "streamType": "m3u",
    "streamUrl": "https://edge22.776740.ir.cdn.ir/hls2/sport.m3u8",
    "githubM3uPath": "",
    "language": "multi",
    "country": "int",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 627,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqzkt29v0fntmk1wjk6pbrdk",
    "name": "bioscope",
    "logo": "https://lh3.googleusercontent.com/mGk98--Wei7SRISqyPRmtGVWYIt9CcyPaQM_8JctgErASaFp91UgCHq_wubRk0SPdtft8gbkRvm1iw5NwcGYj5ftVMIFXhR4EBdY=h200",
    "category": "sports",
    "streamType": "m3u",
    "streamUrl": "https://hls.diptom3ow.workers.dev/r/https%3A%2F%2Ffifa-stream-01.bioscopelive.com%2Fout%2Fv1%2F60e7608404004b1186261497b404630b%2Findex_2.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 848,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmqzmtj5m0ghamk1w1aml79kj",
    "name": "FIFA WC 2026",
    "logo": "https://ssl.gstatic.com/onebox/media/sports/logos/optimized/zRSSLZa7bC9pfCYAf7-DxA_64x64.png",
    "category": "sports,football",
    "streamType": "m3u",
    "streamUrl": "https://andro.226503.xyz/checklist/androstreamliveexn2.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 1020,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmr568nvu07ejqr1weukj0k69",
    "name": "ELTA SPORT 1",
    "logo": "https://play-lh.googleusercontent.com/vE0VONaUjXyEgpUv0efGHg2_GS_Kbmx3YKyWPWzmv8oX-BlTzDReK17V9GhuJ7e7MMmFWvrVyP08vn03Q_H3",
    "category": "sports",
    "streamType": "m3u8",
    "streamUrl": "https://iptv.852851.xyz/l/V46f6o08BGwo1CpYNqSZAZL55DpM6bija9oMQN2452EgR1ivEgrTsNiWt1V2OwFf/index.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 163,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmr808ptv10euqr1wx95wnn9a",
    "name": "First Sports",
    "logo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8sevZPKEWYE3dIAbaMlXOEDT29a3Oltm_G68_mJF3wI3IyWY4Hj1btfI&s=10",
    "category": "sports",
    "streamType": "m3u",
    "streamUrl": "https://a3285273028-s80718.cdn.ngenix.net/hls/CH_FAST_SPORTSHD/video_1920x1080_avc1/playlist.m3u8?profile=web_auto",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 143,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmr80oefw10k6qr1w5z7so1v4",
    "name": "Akash",
    "logo": "https://cdnhost.akashbd.net/assets/images/akash-facebook-banner.jpg?v=10.5.14",
    "category": "sports,entertainment",
    "streamType": "m3u",
    "streamUrl": "https://owrcovcrpy.gpcdn.net/bpk-tv/1720/output/1720-audio_113502_eng=113200-video=2407200.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 284,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  },
  {
    "id": "cmr87u3sl15clqr1wsdx4c3dr",
    "name": "FOX USA",
    "logo": "",
    "category": "entertainment",
    "streamType": "m3u",
    "streamUrl": "https://inproviszon.st/fox-usa.m3u8",
    "githubM3uPath": "",
    "language": "",
    "country": "",
    "tags": "",
    "isFeatured": false,
    "isActive": true,
    "viewCount": 133,
    "sourcePageUrl": "",
    "refreshPattern": "",
    "autoRefresh": false,
    "refreshError": ""
  }
]

export const DEFAULT_CATEGORIES: DefaultCategory[] = [
  {
    "id": "cmqm6nw820kvcmq1v64pbc1e0",
    "name": "Sports",
    "icon": "",
    "color": "#A8E6CF",
    "order": 1,
    "channelCount": 40
  },
  {
    "id": "cmqwa75i90ff9ns1varr7tpb6",
    "name": "FIFA",
    "icon": "",
    "color": "#FFE3B3",
    "order": 2,
    "channelCount": 5
  }
]

export const DEFAULT_SETTINGS = {
  id: 'app',
  appName: 'GenZ TV',
  logoUrl: '',
  maintenanceMode: false,
  featuredChannelId: '',
  heroBannerText: '',
  defaultQuality: 'auto',
  bannerAdScript: '',
  socialBarAdScript: '',
  customAdScripts: '[]',
  adsEnabled: true,
  homeAdsEnabled: true,
  videoAdsEnabled: true,
  apkUrl: '',
  ga4MeasurementId: '',
  firebaseConfig: '{}',
  securityEnabled: true,
  redirectAdUrl: '',
  redirectAdEnabled: false,
  redirectAdIntervalMinutes: 5,
  monetagEnabled: false,
  monetagZoneId: '',
  monetagDomain: '5gvci.com',
}
