// ═══════════════════════════════════════════════════════════
// Teams Database — FIFA Countries, Football Clubs, ICC Countries
// ═══════════════════════════════════════════════════════════

export interface TeamEntry {
  name: string
  logo: string  // flag image URL or club logo URL
  type: 'country' | 'club'
}

// ─── FIFA Member Countries (all 211) ───
export const fifaCountries: TeamEntry[] = [
  // AFC (47 members)
  { name: 'Afghanistan', logo: 'https://flagcdn.com/w320/af.png', type: 'country' },
  { name: 'Australia', logo: 'https://flagcdn.com/w320/au.png', type: 'country' },
  { name: 'Bahrain', logo: 'https://flagcdn.com/w320/bh.png', type: 'country' },
  { name: 'Bangladesh', logo: 'https://flagcdn.com/w320/bd.png', type: 'country' },
  { name: 'Bhutan', logo: 'https://flagcdn.com/w320/bt.png', type: 'country' },
  { name: 'Brunei', logo: 'https://flagcdn.com/w320/bn.png', type: 'country' },
  { name: 'Cambodia', logo: 'https://flagcdn.com/w320/kh.png', type: 'country' },
  { name: 'China', logo: 'https://flagcdn.com/w320/cn.png', type: 'country' },
  { name: 'Chinese Taipei', logo: 'https://flagcdn.com/w320/tw.png', type: 'country' },
  { name: 'Guam', logo: 'https://flagcdn.com/w320/gu.png', type: 'country' },
  { name: 'Hong Kong', logo: 'https://flagcdn.com/w320/hk.png', type: 'country' },
  { name: 'India', logo: 'https://flagcdn.com/w320/in.png', type: 'country' },
  { name: 'Indonesia', logo: 'https://flagcdn.com/w320/id.png', type: 'country' },
  { name: 'Iran', logo: 'https://flagcdn.com/w320/ir.png', type: 'country' },
  { name: 'Iraq', logo: 'https://flagcdn.com/w320/iq.png', type: 'country' },
  { name: 'Japan', logo: 'https://flagcdn.com/w320/jp.png', type: 'country' },
  { name: 'Jordan', logo: 'https://flagcdn.com/w320/jo.png', type: 'country' },
  { name: 'Kuwait', logo: 'https://flagcdn.com/w320/kw.png', type: 'country' },
  { name: 'Kyrgyzstan', logo: 'https://flagcdn.com/w320/kg.png', type: 'country' },
  { name: 'Laos', logo: 'https://flagcdn.com/w320/la.png', type: 'country' },
  { name: 'Lebanon', logo: 'https://flagcdn.com/w320/lb.png', type: 'country' },
  { name: 'Macau', logo: 'https://flagcdn.com/w320/mo.png', type: 'country' },
  { name: 'Malaysia', logo: 'https://flagcdn.com/w320/my.png', type: 'country' },
  { name: 'Maldives', logo: 'https://flagcdn.com/w320/mv.png', type: 'country' },
  { name: 'Mongolia', logo: 'https://flagcdn.com/w320/mn.png', type: 'country' },
  { name: 'Myanmar', logo: 'https://flagcdn.com/w320/mm.png', type: 'country' },
  { name: 'Nepal', logo: 'https://flagcdn.com/w320/np.png', type: 'country' },
  { name: 'North Korea', logo: 'https://flagcdn.com/w320/kp.png', type: 'country' },
  { name: 'Oman', logo: 'https://flagcdn.com/w320/om.png', type: 'country' },
  { name: 'Pakistan', logo: 'https://flagcdn.com/w320/pk.png', type: 'country' },
  { name: 'Palestine', logo: 'https://flagcdn.com/w320/ps.png', type: 'country' },
  { name: 'Philippines', logo: 'https://flagcdn.com/w320/ph.png', type: 'country' },
  { name: 'Qatar', logo: 'https://flagcdn.com/w320/qa.png', type: 'country' },
  { name: 'Saudi Arabia', logo: 'https://flagcdn.com/w320/sa.png', type: 'country' },
  { name: 'Singapore', logo: 'https://flagcdn.com/w320/sg.png', type: 'country' },
  { name: 'South Korea', logo: 'https://flagcdn.com/w320/kr.png', type: 'country' },
  { name: 'Sri Lanka', logo: 'https://flagcdn.com/w320/lk.png', type: 'country' },
  { name: 'Syria', logo: 'https://flagcdn.com/w320/sy.png', type: 'country' },
  { name: 'Tajikistan', logo: 'https://flagcdn.com/w320/tj.png', type: 'country' },
  { name: 'Thailand', logo: 'https://flagcdn.com/w320/th.png', type: 'country' },
  { name: 'Timor-Leste', logo: 'https://flagcdn.com/w320/tl.png', type: 'country' },
  { name: 'Turkmenistan', logo: 'https://flagcdn.com/w320/tm.png', type: 'country' },
  { name: 'United Arab Emirates', logo: 'https://flagcdn.com/w320/ae.png', type: 'country' },
  { name: 'Uzbekistan', logo: 'https://flagcdn.com/w320/uz.png', type: 'country' },
  { name: 'Vietnam', logo: 'https://flagcdn.com/w320/vn.png', type: 'country' },
  { name: 'Yemen', logo: 'https://flagcdn.com/w320/ye.png', type: 'country' },
  // CAF (54 members)
  { name: 'Algeria', logo: 'https://flagcdn.com/w320/dz.png', type: 'country' },
  { name: 'Angola', logo: 'https://flagcdn.com/w320/ao.png', type: 'country' },
  { name: 'Benin', logo: 'https://flagcdn.com/w320/bj.png', type: 'country' },
  { name: 'Botswana', logo: 'https://flagcdn.com/w320/bw.png', type: 'country' },
  { name: 'Burkina Faso', logo: 'https://flagcdn.com/w320/bf.png', type: 'country' },
  { name: 'Burundi', logo: 'https://flagcdn.com/w320/bi.png', type: 'country' },
  { name: 'Cameroon', logo: 'https://flagcdn.com/w320/cm.png', type: 'country' },
  { name: 'Cape Verde', logo: 'https://flagcdn.com/w320/cv.png', type: 'country' },
  { name: 'Central African Republic', logo: 'https://flagcdn.com/w320/cf.png', type: 'country' },
  { name: 'Chad', logo: 'https://flagcdn.com/w320/td.png', type: 'country' },
  { name: 'Comoros', logo: 'https://flagcdn.com/w320/km.png', type: 'country' },
  { name: 'Congo', logo: 'https://flagcdn.com/w320/cg.png', type: 'country' },
  { name: 'DR Congo', logo: 'https://flagcdn.com/w320/cd.png', type: 'country' },
  { name: 'Djibouti', logo: 'https://flagcdn.com/w320/dj.png', type: 'country' },
  { name: 'Egypt', logo: 'https://flagcdn.com/w320/eg.png', type: 'country' },
  { name: 'Equatorial Guinea', logo: 'https://flagcdn.com/w320/gq.png', type: 'country' },
  { name: 'Eritrea', logo: 'https://flagcdn.com/w320/er.png', type: 'country' },
  { name: 'Eswatini', logo: 'https://flagcdn.com/w320/sz.png', type: 'country' },
  { name: 'Ethiopia', logo: 'https://flagcdn.com/w320/et.png', type: 'country' },
  { name: 'Gabon', logo: 'https://flagcdn.com/w320/ga.png', type: 'country' },
  { name: 'Gambia', logo: 'https://flagcdn.com/w320/gm.png', type: 'country' },
  { name: 'Ghana', logo: 'https://flagcdn.com/w320/gh.png', type: 'country' },
  { name: 'Guinea', logo: 'https://flagcdn.com/w320/gn.png', type: 'country' },
  { name: 'Guinea-Bissau', logo: 'https://flagcdn.com/w320/gw.png', type: 'country' },
  { name: 'Ivory Coast', logo: 'https://flagcdn.com/w320/ci.png', type: 'country' },
  { name: 'Kenya', logo: 'https://flagcdn.com/w320/ke.png', type: 'country' },
  { name: 'Lesotho', logo: 'https://flagcdn.com/w320/ls.png', type: 'country' },
  { name: 'Liberia', logo: 'https://flagcdn.com/w320/lr.png', type: 'country' },
  { name: 'Libya', logo: 'https://flagcdn.com/w320/ly.png', type: 'country' },
  { name: 'Madagascar', logo: 'https://flagcdn.com/w320/mg.png', type: 'country' },
  { name: 'Malawi', logo: 'https://flagcdn.com/w320/mw.png', type: 'country' },
  { name: 'Mali', logo: 'https://flagcdn.com/w320/ml.png', type: 'country' },
  { name: 'Mauritania', logo: 'https://flagcdn.com/w320/mr.png', type: 'country' },
  { name: 'Mauritius', logo: 'https://flagcdn.com/w320/mu.png', type: 'country' },
  { name: 'Morocco', logo: 'https://flagcdn.com/w320/ma.png', type: 'country' },
  { name: 'Mozambique', logo: 'https://flagcdn.com/w320/mz.png', type: 'country' },
  { name: 'Namibia', logo: 'https://flagcdn.com/w320/na.png', type: 'country' },
  { name: 'Niger', logo: 'https://flagcdn.com/w320/ne.png', type: 'country' },
  { name: 'Nigeria', logo: 'https://flagcdn.com/w320/ng.png', type: 'country' },
  { name: 'Rwanda', logo: 'https://flagcdn.com/w320/rw.png', type: 'country' },
  { name: 'São Tomé and Príncipe', logo: 'https://flagcdn.com/w320/st.png', type: 'country' },
  { name: 'Senegal', logo: 'https://flagcdn.com/w320/sn.png', type: 'country' },
  { name: 'Seychelles', logo: 'https://flagcdn.com/w320/sc.png', type: 'country' },
  { name: 'Sierra Leone', logo: 'https://flagcdn.com/w320/sl.png', type: 'country' },
  { name: 'Somalia', logo: 'https://flagcdn.com/w320/so.png', type: 'country' },
  { name: 'South Africa', logo: 'https://flagcdn.com/w320/za.png', type: 'country' },
  { name: 'South Sudan', logo: 'https://flagcdn.com/w320/ss.png', type: 'country' },
  { name: 'Sudan', logo: 'https://flagcdn.com/w320/sd.png', type: 'country' },
  { name: 'Tanzania', logo: 'https://flagcdn.com/w320/tz.png', type: 'country' },
  { name: 'Togo', logo: 'https://flagcdn.com/w320/tg.png', type: 'country' },
  { name: 'Tunisia', logo: 'https://flagcdn.com/w320/tn.png', type: 'country' },
  { name: 'Uganda', logo: 'https://flagcdn.com/w320/ug.png', type: 'country' },
  { name: 'Zambia', logo: 'https://flagcdn.com/w320/zm.png', type: 'country' },
  { name: 'Zimbabwe', logo: 'https://flagcdn.com/w320/zw.png', type: 'country' },
  // CONCACAF (41 members)
  { name: 'Antigua and Barbuda', logo: 'https://flagcdn.com/w320/ag.png', type: 'country' },
  { name: 'Bahamas', logo: 'https://flagcdn.com/w320/bs.png', type: 'country' },
  { name: 'Barbados', logo: 'https://flagcdn.com/w320/bb.png', type: 'country' },
  { name: 'Belize', logo: 'https://flagcdn.com/w320/bz.png', type: 'country' },
  { name: 'Canada', logo: 'https://flagcdn.com/w320/ca.png', type: 'country' },
  { name: 'Costa Rica', logo: 'https://flagcdn.com/w320/cr.png', type: 'country' },
  { name: 'Cuba', logo: 'https://flagcdn.com/w320/cu.png', type: 'country' },
  { name: 'Dominica', logo: 'https://flagcdn.com/w320/dm.png', type: 'country' },
  { name: 'Dominican Republic', logo: 'https://flagcdn.com/w320/do.png', type: 'country' },
  { name: 'El Salvador', logo: 'https://flagcdn.com/w320/sv.png', type: 'country' },
  { name: 'Grenada', logo: 'https://flagcdn.com/w320/gd.png', type: 'country' },
  { name: 'Guatemala', logo: 'https://flagcdn.com/w320/gt.png', type: 'country' },
  { name: 'Guyana', logo: 'https://flagcdn.com/w320/gy.png', type: 'country' },
  { name: 'Haiti', logo: 'https://flagcdn.com/w320/ht.png', type: 'country' },
  { name: 'Honduras', logo: 'https://flagcdn.com/w320/hn.png', type: 'country' },
  { name: 'Jamaica', logo: 'https://flagcdn.com/w320/jm.png', type: 'country' },
  { name: 'Mexico', logo: 'https://flagcdn.com/w320/mx.png', type: 'country' },
  { name: 'Nicaragua', logo: 'https://flagcdn.com/w320/ni.png', type: 'country' },
  { name: 'Panama', logo: 'https://flagcdn.com/w320/pa.png', type: 'country' },
  { name: 'Saint Kitts and Nevis', logo: 'https://flagcdn.com/w320/kn.png', type: 'country' },
  { name: 'Saint Lucia', logo: 'https://flagcdn.com/w320/lc.png', type: 'country' },
  { name: 'Saint Vincent and the Grenadines', logo: 'https://flagcdn.com/w320/vc.png', type: 'country' },
  { name: 'Suriname', logo: 'https://flagcdn.com/w320/sr.png', type: 'country' },
  { name: 'Trinidad and Tobago', logo: 'https://flagcdn.com/w320/tt.png', type: 'country' },
  { name: 'United States', logo: 'https://flagcdn.com/w320/us.png', type: 'country' },
  { name: 'Curaçao', logo: 'https://flagcdn.com/w320/cw.png', type: 'country' },
  { name: 'Bonaire', logo: 'https://flagcdn.com/w320/bq.png', type: 'country' },
  { name: 'Sint Maarten', logo: 'https://flagcdn.com/w320/sx.png', type: 'country' },
  { name: 'Saint Martin', logo: 'https://flagcdn.com/w320/mf.png', type: 'country' },
  { name: 'Greenland', logo: 'https://flagcdn.com/w320/gl.png', type: 'country' },
  { name: 'Puerto Rico', logo: 'https://flagcdn.com/w320/pr.png', type: 'country' },
  { name: 'United States Virgin Islands', logo: 'https://flagcdn.com/w320/vi.png', type: 'country' },
  { name: 'Northern Mariana Islands', logo: 'https://flagcdn.com/w320/mp.png', type: 'country' },
  { name: 'American Samoa', logo: 'https://flagcdn.com/w320/as.png', type: 'country' },
  // CONMEBOL (10 members)
  { name: 'Argentina', logo: 'https://flagcdn.com/w320/ar.png', type: 'country' },
  { name: 'Bolivia', logo: 'https://flagcdn.com/w320/bo.png', type: 'country' },
  { name: 'Brazil', logo: 'https://flagcdn.com/w320/br.png', type: 'country' },
  { name: 'Chile', logo: 'https://flagcdn.com/w320/cl.png', type: 'country' },
  { name: 'Colombia', logo: 'https://flagcdn.com/w320/co.png', type: 'country' },
  { name: 'Ecuador', logo: 'https://flagcdn.com/w320/ec.png', type: 'country' },
  { name: 'Paraguay', logo: 'https://flagcdn.com/w320/py.png', type: 'country' },
  { name: 'Peru', logo: 'https://flagcdn.com/w320/pe.png', type: 'country' },
  { name: 'Uruguay', logo: 'https://flagcdn.com/w320/uy.png', type: 'country' },
  { name: 'Venezuela', logo: 'https://flagcdn.com/w320/ve.png', type: 'country' },
  // OFC (13 members)
  { name: 'American Samoa', logo: 'https://flagcdn.com/w320/as.png', type: 'country' },
  { name: 'Cook Islands', logo: 'https://flagcdn.com/w320/ck.png', type: 'country' },
  { name: 'Fiji', logo: 'https://flagcdn.com/w320/fj.png', type: 'country' },
  { name: 'New Caledonia', logo: 'https://flagcdn.com/w320/nc.png', type: 'country' },
  { name: 'New Zealand', logo: 'https://flagcdn.com/w320/nz.png', type: 'country' },
  { name: 'Papua New Guinea', logo: 'https://flagcdn.com/w320/pg.png', type: 'country' },
  { name: 'Samoa', logo: 'https://flagcdn.com/w320/ws.png', type: 'country' },
  { name: 'Solomon Islands', logo: 'https://flagcdn.com/w320/sb.png', type: 'country' },
  { name: 'Tahiti', logo: 'https://flagcdn.com/w320/pf.png', type: 'country' },
  { name: 'Tonga', logo: 'https://flagcdn.com/w320/to.png', type: 'country' },
  { name: 'Vanuatu', logo: 'https://flagcdn.com/w320/vu.png', type: 'country' },
  // UEFA (55 members)
  { name: 'Albania', logo: 'https://flagcdn.com/w320/al.png', type: 'country' },
  { name: 'Andorra', logo: 'https://flagcdn.com/w320/ad.png', type: 'country' },
  { name: 'Armenia', logo: 'https://flagcdn.com/w320/am.png', type: 'country' },
  { name: 'Austria', logo: 'https://flagcdn.com/w320/at.png', type: 'country' },
  { name: 'Azerbaijan', logo: 'https://flagcdn.com/w320/az.png', type: 'country' },
  { name: 'Belarus', logo: 'https://flagcdn.com/w320/by.png', type: 'country' },
  { name: 'Belgium', logo: 'https://flagcdn.com/w320/be.png', type: 'country' },
  { name: 'Bosnia and Herzegovina', logo: 'https://flagcdn.com/w320/ba.png', type: 'country' },
  { name: 'Bulgaria', logo: 'https://flagcdn.com/w320/bg.png', type: 'country' },
  { name: 'Croatia', logo: 'https://flagcdn.com/w320/hr.png', type: 'country' },
  { name: 'Cyprus', logo: 'https://flagcdn.com/w320/cy.png', type: 'country' },
  { name: 'Czech Republic', logo: 'https://flagcdn.com/w320/cz.png', type: 'country' },
  { name: 'Denmark', logo: 'https://flagcdn.com/w320/dk.png', type: 'country' },
  { name: 'England', logo: 'https://flagcdn.com/w320/gb-eng.png', type: 'country' },
  { name: 'Estonia', logo: 'https://flagcdn.com/w320/ee.png', type: 'country' },
  { name: 'Faroe Islands', logo: 'https://flagcdn.com/w320/fo.png', type: 'country' },
  { name: 'Finland', logo: 'https://flagcdn.com/w320/fi.png', type: 'country' },
  { name: 'France', logo: 'https://flagcdn.com/w320/fr.png', type: 'country' },
  { name: 'Georgia', logo: 'https://flagcdn.com/w320/ge.png', type: 'country' },
  { name: 'Germany', logo: 'https://flagcdn.com/w320/de.png', type: 'country' },
  { name: 'Gibraltar', logo: 'https://flagcdn.com/w320/gi.png', type: 'country' },
  { name: 'Greece', logo: 'https://flagcdn.com/w320/gr.png', type: 'country' },
  { name: 'Hungary', logo: 'https://flagcdn.com/w320/hu.png', type: 'country' },
  { name: 'Iceland', logo: 'https://flagcdn.com/w320/is.png', type: 'country' },
  { name: 'Israel', logo: 'https://flagcdn.com/w320/il.png', type: 'country' },
  { name: 'Italy', logo: 'https://flagcdn.com/w320/it.png', type: 'country' },
  { name: 'Kazakhstan', logo: 'https://flagcdn.com/w320/kz.png', type: 'country' },
  { name: 'Kosovo', logo: 'https://flagcdn.com/w320/xk.png', type: 'country' },
  { name: 'Latvia', logo: 'https://flagcdn.com/w320/lv.png', type: 'country' },
  { name: 'Liechtenstein', logo: 'https://flagcdn.com/w320/li.png', type: 'country' },
  { name: 'Lithuania', logo: 'https://flagcdn.com/w320/lt.png', type: 'country' },
  { name: 'Luxembourg', logo: 'https://flagcdn.com/w320/lu.png', type: 'country' },
  { name: 'Malta', logo: 'https://flagcdn.com/w320/mt.png', type: 'country' },
  { name: 'Moldova', logo: 'https://flagcdn.com/w320/md.png', type: 'country' },
  { name: 'Monaco', logo: 'https://flagcdn.com/w320/mc.png', type: 'country' },
  { name: 'Montenegro', logo: 'https://flagcdn.com/w320/me.png', type: 'country' },
  { name: 'Netherlands', logo: 'https://flagcdn.com/w320/nl.png', type: 'country' },
  { name: 'North Macedonia', logo: 'https://flagcdn.com/w320/mk.png', type: 'country' },
  { name: 'Northern Ireland', logo: 'https://flagcdn.com/w320/gb-nir.png', type: 'country' },
  { name: 'Norway', logo: 'https://flagcdn.com/w320/no.png', type: 'country' },
  { name: 'Poland', logo: 'https://flagcdn.com/w320/pl.png', type: 'country' },
  { name: 'Portugal', logo: 'https://flagcdn.com/w320/pt.png', type: 'country' },
  { name: 'Republic of Ireland', logo: 'https://flagcdn.com/w320/ie.png', type: 'country' },
  { name: 'Romania', logo: 'https://flagcdn.com/w320/ro.png', type: 'country' },
  { name: 'Russia', logo: 'https://flagcdn.com/w320/ru.png', type: 'country' },
  { name: 'San Marino', logo: 'https://flagcdn.com/w320/sm.png', type: 'country' },
  { name: 'Scotland', logo: 'https://flagcdn.com/w320/gb-sct.png', type: 'country' },
  { name: 'Serbia', logo: 'https://flagcdn.com/w320/rs.png', type: 'country' },
  { name: 'Slovakia', logo: 'https://flagcdn.com/w320/sk.png', type: 'country' },
  { name: 'Slovenia', logo: 'https://flagcdn.com/w320/si.png', type: 'country' },
  { name: 'Spain', logo: 'https://flagcdn.com/w320/es.png', type: 'country' },
  { name: 'Sweden', logo: 'https://flagcdn.com/w320/se.png', type: 'country' },
  { name: 'Switzerland', logo: 'https://flagcdn.com/w320/ch.png', type: 'country' },
  { name: 'Turkey', logo: 'https://flagcdn.com/w320/tr.png', type: 'country' },
  { name: 'Ukraine', logo: 'https://flagcdn.com/w320/ua.png', type: 'country' },
  { name: 'Wales', logo: 'https://flagcdn.com/w320/gb-wls.png', type: 'country' },
  { name: 'Vatican City', logo: 'https://flagcdn.com/w320/va.png', type: 'country' },
  { name: 'Somaliland', logo: 'https://flagcdn.com/w320/so.png', type: 'country' },
  { name: 'Western Sahara', logo: 'https://flagcdn.com/w320/eh.png', type: 'country' },
  { name: 'Falkland Islands', logo: 'https://flagcdn.com/w320/fk.png', type: 'country' },
  { name: 'Gibraltar', logo: 'https://flagcdn.com/w320/gi.png', type: 'country' },
  { name: 'Isle of Man', logo: 'https://flagcdn.com/w320/im.png', type: 'country' },
  { name: 'Jersey', logo: 'https://flagcdn.com/w320/je.png', type: 'country' },
  { name: 'Guernsey', logo: 'https://flagcdn.com/w320/gg.png', type: 'country' },
  { name: 'Faroe Islands', logo: 'https://flagcdn.com/w320/fo.png', type: 'country' },
  { name: 'Åland Islands', logo: 'https://flagcdn.com/w320/ax.png', type: 'country' },
]

// ─── Popular Football Clubs with Logo URLs ───
export const footballClubs: TeamEntry[] = [
  // Premier League
  { name: 'Manchester City', logo: 'https://assets.footylogos.com/logos/manchester-city/manchester-city-logo-footylogos.png', type: 'club' },
  { name: 'Liverpool', logo: 'https://assets.footylogos.com/logos/liverpool-fc/liverpool-fc-logo-footylogos.png', type: 'club' },
  { name: 'Arsenal', logo: 'https://assets.footylogos.com/logos/arsenal/arsenal-logo-footylogos.png', type: 'club' },
  { name: 'Chelsea', logo: 'https://assets.footylogos.com/logos/chelsea/chelsea-logo-footylogos.png', type: 'club' },
  { name: 'Manchester United', logo: 'https://assets.footylogos.com/logos/manchester-united/manchester-united-logo-footylogos.png', type: 'club' },
  { name: 'Tottenham Hotspur', logo: 'https://assets.footylogos.com/logos/tottenham-hotspur/tottenham-hotspur-logo-footylogos.png', type: 'club' },
  { name: 'Newcastle United', logo: 'https://assets.footylogos.com/logos/newcastle-united/newcastle-united-logo-footylogos.png', type: 'club' },
  { name: 'Aston Villa', logo: 'https://assets.footylogos.com/logos/aston-villa/aston-villa-logo-footylogos.png', type: 'club' },
  { name: 'Brighton', logo: 'https://assets.footylogos.com/logos/brighton-and-hove-albion/brighton-and-hove-albion-logo-footylogos.png', type: 'club' },
  { name: 'West Ham', logo: 'https://assets.footylogos.com/logos/west-ham-united/west-ham-united-logo-footylogos.png', type: 'club' },
  { name: 'Crystal Palace', logo: 'https://assets.footylogos.com/logos/crystal-palace/crystal-palace-logo-footylogos.png', type: 'club' },
  { name: 'Everton', logo: 'https://assets.footylogos.com/logos/everton/everton-logo-footylogos.png', type: 'club' },
  { name: 'Fulham', logo: 'https://assets.footylogos.com/logos/fulham/fulham-logo-footylogos.png', type: 'club' },
  { name: 'Wolves', logo: 'https://assets.footylogos.com/logos/wolverhampton-wanderers/wolverhampton-wanderers-logo-footylogos.png', type: 'club' },
  { name: 'Bournemouth', logo: 'https://assets.footylogos.com/logos/afc-bournemouth/afc-bournemouth-logo-footylogos.png', type: 'club' },
  { name: 'Nottingham Forest', logo: 'https://assets.footylogos.com/logos/nottingham-forest/nottingham-forest-logo-footylogos.png', type: 'club' },
  { name: 'Brentford', logo: 'https://assets.footylogos.com/logos/brentford/brentford-logo-footylogos.png', type: 'club' },
  { name: 'Leicester City', logo: 'https://assets.footylogos.com/logos/leicester/leicester-logo-footylogos.png', type: 'club' },
  { name: 'Ipswich Town', logo: 'https://assets.footylogos.com/logos/ipswich-town/ipswich-town-logo-footylogos.png', type: 'club' },
  { name: 'Southampton', logo: 'https://assets.footylogos.com/logos/southampton/southampton-logo-footylogos.png', type: 'club' },
  // La Liga
  { name: 'Real Madrid', logo: 'https://assets.footylogos.com/logos/real-madrid/real-madrid-logo-footylogos.png', type: 'club' },
  { name: 'Barcelona', logo: 'https://assets.footylogos.com/logos/fc-barcelona/fc-barcelona-logo-footylogos.png', type: 'club' },
  { name: 'Atlético Madrid', logo: 'https://assets.footylogos.com/logos/atletico-madrid/atletico-madrid-logo-footylogos.png', type: 'club' },
  { name: 'Real Sociedad', logo: 'https://assets.footylogos.com/logos/real-sociedad/real-sociedad-logo-footylogos.png', type: 'club' },
  { name: 'Real Betis', logo: 'https://assets.footylogos.com/logos/real-betis-balompie/real-betis-balompie-logo-footylogos.png', type: 'club' },
  { name: 'Sevilla', logo: 'https://assets.footylogos.com/logos/sevilla-fc/sevilla-fc-logo-footylogos.png', type: 'club' },
  { name: 'Villarreal', logo: 'https://assets.footylogos.com/logos/villarreal-cf/villarreal-cf-logo-footylogos.png', type: 'club' },
  { name: 'Athletic Bilbao', logo: 'https://assets.footylogos.com/logos/athletic-club-bilbao/athletic-club-bilbao-logo-footylogos.png', type: 'club' },
  { name: 'Valencia', logo: 'https://assets.footylogos.com/logos/valencia-cf/valencia-cf-logo-footylogos.png', type: 'club' },
  // Serie A
  { name: 'Inter Milan', logo: 'https://assets.footylogos.com/logos/inter-milan/inter-milan-logo-footylogos.png', type: 'club' },
  { name: 'AC Milan', logo: 'https://assets.footylogos.com/logos/ac-milan/ac-milan-logo-footylogos.png', type: 'club' },
  { name: 'Juventus', logo: 'https://assets.footylogos.com/logos/juventus/juventus-logo-footylogos.png', type: 'club' },
  { name: 'Napoli', logo: 'https://assets.footylogos.com/logos/napoli/napoli-logo-footylogos.png', type: 'club' },
  { name: 'AS Roma', logo: 'https://assets.footylogos.com/logos/roma/roma-logo-footylogos.png', type: 'club' },
  { name: 'Lazio', logo: 'https://assets.footylogos.com/logos/lazio/lazio-logo-footylogos.png', type: 'club' },
  { name: 'Atalanta', logo: 'https://assets.footylogos.com/logos/atalanta/atalanta-logo-footylogos.png', type: 'club' },
  { name: 'Fiorentina', logo: 'https://assets.footylogos.com/logos/fiorentina/fiorentina-logo-footylogos.png', type: 'club' },
  // Bundesliga
  { name: 'Bayern Munich', logo: 'https://assets.footylogos.com/logos/bayern-munich/bayern-munich-logo-footylogos.png', type: 'club' },
  { name: 'Borussia Dortmund', logo: 'https://assets.footylogos.com/logos/borussia-dortmund/borussia-dortmund-logo-footylogos.png', type: 'club' },
  { name: 'RB Leipzig', logo: 'https://assets.footylogos.com/logos/rb-leipzig/rb-leipzig-logo-footylogos.png', type: 'club' },
  { name: 'Bayer Leverkusen', logo: 'https://assets.footylogos.com/logos/bayer-leverkusen/bayer-leverkusen-logo-footylogos.png', type: 'club' },
  { name: 'VfB Stuttgart', logo: 'https://assets.footylogos.com/logos/vfb-stuttgart/vfb-stuttgart-logo-footylogos.png', type: 'club' },
  { name: 'Eintracht Frankfurt', logo: 'https://assets.footylogos.com/logos/eintracht-frankfurt/eintracht-frankfurt-logo-footylogos.png', type: 'club' },
  { name: 'SC Freiburg', logo: 'https://assets.footylogos.com/logos/sc-freiburg/sc-freiburg-logo-footylogos.png', type: 'club' },
  { name: 'Wolfsburg', logo: 'https://assets.footylogos.com/logos/vfl-wolfsburg/vfl-wolfsburg-logo-footylogos.png', type: 'club' },
  { name: 'Borussia Mönchengladbach', logo: 'https://assets.footylogos.com/logos/borussia-monchengladbach/borussia-monchengladbach-logo-footylogos.png', type: 'club' },
  // Ligue 1
  { name: 'PSG', logo: 'https://assets.footylogos.com/logos/paris-saint-germain-psg/paris-saint-germain-psg-logo-footylogos.png', type: 'club' },
  { name: 'Marseille', logo: 'https://assets.footylogos.com/logos/olympique-de-marseille-om/olympique-de-marseille-om-logo-footylogos.png', type: 'club' },
  { name: 'Monaco', logo: 'https://assets.footylogos.com/logos/as-monaco/as-monaco-logo-footylogos.png', type: 'club' },
  { name: 'Lyon', logo: 'https://assets.footylogos.com/logos/olympique-lyonnais/olympique-lyonnais-logo-footylogos.png', type: 'club' },
  { name: 'Lille', logo: 'https://assets.footylogos.com/logos/losc-lille/losc-lille-logo-footylogos.png', type: 'club' },
  { name: 'Nice', logo: 'https://assets.footylogos.com/logos/ogc-nice/ogc-nice-logo-footylogos.png', type: 'club' },
  { name: 'Lens', logo: 'https://assets.footylogos.com/logos/rc-lens/rc-lens-logo-footylogos.png', type: 'club' },
  // Eredivisie
  { name: 'Ajax', logo: 'https://assets.footylogos.com/logos/ajax/ajax-logo-footylogos.png', type: 'club' },
  { name: 'PSV', logo: 'https://assets.footylogos.com/logos/psv-eindhoven/psv-eindhoven-logo-footylogos.png', type: 'club' },
  { name: 'Feyenoord', logo: 'https://assets.footylogos.com/logos/feyenoord/feyenoord-logo-footylogos.png', type: 'club' },
  // Primeira Liga
  { name: 'Benfica', logo: 'https://assets.footylogos.com/logos/sl-benfica/sl-benfica-logo-footylogos.png', type: 'club' },
  { name: 'Porto', logo: 'https://assets.footylogos.com/logos/fc-porto/fc-porto-logo-footylogos.png', type: 'club' },
  { name: 'Sporting CP', logo: 'https://assets.footylogos.com/logos/sporting-cp/sporting-cp-logo-footylogos.png', type: 'club' },
  // Other notable clubs
  { name: 'Celtic', logo: 'https://assets.footylogos.com/logos/celtic/celtic-logo-footylogos.png', type: 'club' },
  { name: 'Rangers', logo: 'https://assets.footylogos.com/logos/rangers/rangers-logo-footylogos.png', type: 'club' },
  { name: 'Galatasaray', logo: 'https://assets.footylogos.com/logos/galatasaray/galatasaray-logo-footylogos.png', type: 'club' },
  { name: 'Fenerbahçe', logo: 'https://assets.footylogos.com/logos/fenerbahce/fenerbahce-logo-footylogos.png', type: 'club' },
  { name: 'Besiktas', logo: 'https://assets.footylogos.com/logos/besiktas/besiktas-logo-footylogos.png', type: 'club' },
  { name: 'Al Hilal', logo: 'https://assets.footylogos.com/logos/al-hilal/al-hilal-logo-footylogos.png', type: 'club' },
  { name: 'Al Nassr', logo: 'https://assets.footylogos.com/logos/al-nassr/al-nassr-logo-footylogos.png', type: 'club' },
  { name: 'Al Ahli', logo: 'https://assets.footylogos.com/logos/al-ahli/al-ahli-logo-footylogos.png', type: 'club' },
  { name: 'Al Ittihad', logo: 'https://assets.footylogos.com/logos/al-ittihad/al-ittihad-logo-footylogos.png', type: 'club' },
  // MLS
  { name: 'Inter Miami', logo: 'https://assets.footylogos.com/logos/inter-miami/inter-miami-logo-footylogos.png', type: 'club' },
  { name: 'LA Galaxy', logo: 'https://assets.footylogos.com/logos/la-galaxy/la-galaxy-logo-footylogos.png', type: 'club' },
  { name: 'New York City FC', logo: 'https://assets.footylogos.com/logos/new-york-city-fc/new-york-city-fc-logo-footylogos.png', type: 'club' },
  // Argentine clubs
  { name: 'River Plate', logo: 'https://assets.footylogos.com/logos/river-plate/river-plate-logo-footylogos.png', type: 'club' },
  { name: 'Boca Juniors', logo: 'https://assets.footylogos.com/logos/boca-juniors/boca-juniors-logo-footylogos.png', type: 'club' },
]

// ─── ICC Member Countries (Full Members + Associates) ───
export const iccCountries: TeamEntry[] = [
  // Full Members (12)
  { name: 'Australia', logo: 'https://flagcdn.com/w320/au.png', type: 'country' },
  { name: 'England', logo: 'https://flagcdn.com/w320/gb-eng.png', type: 'country' },
  { name: 'India', logo: 'https://flagcdn.com/w320/in.png', type: 'country' },
  { name: 'New Zealand', logo: 'https://flagcdn.com/w320/nz.png', type: 'country' },
  { name: 'Pakistan', logo: 'https://flagcdn.com/w320/pk.png', type: 'country' },
  { name: 'South Africa', logo: 'https://flagcdn.com/w320/za.png', type: 'country' },
  { name: 'Sri Lanka', logo: 'https://flagcdn.com/w320/lk.png', type: 'country' },
  { name: 'West Indies', logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/7/7e/West_Indies_Cricket_Board_logo.svg/200px-West_Indies_Cricket_Board_logo.svg.png', type: 'country' },
  { name: 'Bangladesh', logo: 'https://flagcdn.com/w320/bd.png', type: 'country' },
  { name: 'Zimbabwe', logo: 'https://flagcdn.com/w320/zw.png', type: 'country' },
  { name: 'Ireland', logo: 'https://flagcdn.com/w320/ie.png', type: 'country' },
  { name: 'Afghanistan', logo: 'https://flagcdn.com/w320/af.png', type: 'country' },
  // Associate Members
  { name: 'Netherlands', logo: 'https://flagcdn.com/w320/nl.png', type: 'country' },
  { name: 'Scotland', logo: 'https://flagcdn.com/w320/gb-sct.png', type: 'country' },
  { name: 'Nepal', logo: 'https://flagcdn.com/w320/np.png', type: 'country' },
  { name: 'Namibia', logo: 'https://flagcdn.com/w320/na.png', type: 'country' },
  { name: 'Oman', logo: 'https://flagcdn.com/w320/om.png', type: 'country' },
  { name: 'UAE', logo: 'https://flagcdn.com/w320/ae.png', type: 'country' },
  { name: 'USA', logo: 'https://flagcdn.com/w320/us.png', type: 'country' },
  { name: 'Canada', logo: 'https://flagcdn.com/w320/ca.png', type: 'country' },
  { name: 'Bermuda', logo: 'https://flagcdn.com/w320/bm.png', type: 'country' },
  { name: 'Kenya', logo: 'https://flagcdn.com/w320/ke.png', type: 'country' },
  { name: 'Uganda', logo: 'https://flagcdn.com/w320/ug.png', type: 'country' },
  { name: 'Italy', logo: 'https://flagcdn.com/w320/it.png', type: 'country' },
  { name: 'Denmark', logo: 'https://flagcdn.com/w320/dk.png', type: 'country' },
  { name: 'Guernsey', logo: 'https://flagcdn.com/w320/gg.png', type: 'country' },
  { name: 'Jersey', logo: 'https://flagcdn.com/w320/je.png', type: 'country' },
  { name: 'Malaysia', logo: 'https://flagcdn.com/w320/my.png', type: 'country' },
  { name: 'Singapore', logo: 'https://flagcdn.com/w320/sg.png', type: 'country' },
  { name: 'Papua New Guinea', logo: 'https://flagcdn.com/w320/pg.png', type: 'country' },
  { name: 'Qatar', logo: 'https://flagcdn.com/w320/qa.png', type: 'country' },
  { name: 'Saudi Arabia', logo: 'https://flagcdn.com/w320/sa.png', type: 'country' },
  { name: 'Bahrain', logo: 'https://flagcdn.com/w320/bh.png', type: 'country' },
  { name: 'Kuwait', logo: 'https://flagcdn.com/w320/kw.png', type: 'country' },
  { name: 'Thailand', logo: 'https://flagcdn.com/w320/th.png', type: 'country' },
  { name: 'Zambia', logo: 'https://flagcdn.com/w320/zm.png', type: 'country' },
  { name: 'Nigeria', logo: 'https://flagcdn.com/w320/ng.png', type: 'country' },
  { name: 'Tanzania', logo: 'https://flagcdn.com/w320/tz.png', type: 'country' },
  { name: 'Vanuatu', logo: 'https://flagcdn.com/w320/vu.png', type: 'country' },
  { name: 'Maldives', logo: 'https://flagcdn.com/w320/mv.png', type: 'country' },
  { name: 'Botswana', logo: 'https://flagcdn.com/w320/bw.png', type: 'country' },
]

/**
 * Get teams filtered by sport type
 */
export function getTeamsForSport(sport: string): TeamEntry[] {
  if (sport === 'football') {
    return [...footballClubs, ...fifaCountries]
  }
  if (sport === 'cricket') {
    return iccCountries
  }
  return fifaCountries
}

/**
 * Search teams by name (case-insensitive, partial match)
 * Priority: 1) name starts with query, 2) clubs before countries, 3) contains query
 */
export function searchTeams(query: string, sport: string, limit = 8): TeamEntry[] {
  const teams = getTeamsForSport(sport)
  if (!query.trim()) return teams.slice(0, limit)
  const q = query.toLowerCase()

  const startsWith = teams.filter(t => t.name.toLowerCase().startsWith(q))
  const contains = teams.filter(t => !t.name.toLowerCase().startsWith(q) && t.name.toLowerCase().includes(q))

  // Sort each group: clubs first, then countries
  const sortFn = (a: TeamEntry, b: TeamEntry) => {
    if (a.type === 'club' && b.type !== 'club') return -1
    if (a.type !== 'club' && b.type === 'club') return 1
    return 0
  }

  return [...startsWith.sort(sortFn), ...contains.sort(sortFn)].slice(0, limit)
}
