// ═══════════════════════════════════════════════════════════
// Teams Database — FIFA Countries, Football Clubs, ICC Countries
// ═══════════════════════════════════════════════════════════

export interface TeamEntry {
  name: string
  logo: string  // flag image URL or club logo URL
  type: 'country' | 'club'
}

// ─── FIFA Member Countries (all 211) ───
export const fifaCountries: TeamEntry[] = [
  // AFC (47 members)
  { name: 'Afghanistan', logo: 'https://flagcdn.com/w80/af.png', type: 'country' },
  { name: 'Australia', logo: 'https://flagcdn.com/w80/au.png', type: 'country' },
  { name: 'Bahrain', logo: 'https://flagcdn.com/w80/bh.png', type: 'country' },
  { name: 'Bangladesh', logo: 'https://flagcdn.com/w80/bd.png', type: 'country' },
  { name: 'Bhutan', logo: 'https://flagcdn.com/w80/bt.png', type: 'country' },
  { name: 'Brunei', logo: 'https://flagcdn.com/w80/bn.png', type: 'country' },
  { name: 'Cambodia', logo: 'https://flagcdn.com/w80/kh.png', type: 'country' },
  { name: 'China', logo: 'https://flagcdn.com/w80/cn.png', type: 'country' },
  { name: 'Chinese Taipei', logo: 'https://flagcdn.com/w80/tw.png', type: 'country' },
  { name: 'Guam', logo: 'https://flagcdn.com/w80/gu.png', type: 'country' },
  { name: 'Hong Kong', logo: 'https://flagcdn.com/w80/hk.png', type: 'country' },
  { name: 'India', logo: 'https://flagcdn.com/w80/in.png', type: 'country' },
  { name: 'Indonesia', logo: 'https://flagcdn.com/w80/id.png', type: 'country' },
  { name: 'Iran', logo: 'https://flagcdn.com/w80/ir.png', type: 'country' },
  { name: 'Iraq', logo: 'https://flagcdn.com/w80/iq.png', type: 'country' },
  { name: 'Japan', logo: 'https://flagcdn.com/w80/jp.png', type: 'country' },
  { name: 'Jordan', logo: 'https://flagcdn.com/w80/jo.png', type: 'country' },
  { name: 'Kuwait', logo: 'https://flagcdn.com/w80/kw.png', type: 'country' },
  { name: 'Kyrgyzstan', logo: 'https://flagcdn.com/w80/kg.png', type: 'country' },
  { name: 'Laos', logo: 'https://flagcdn.com/w80/la.png', type: 'country' },
  { name: 'Lebanon', logo: 'https://flagcdn.com/w80/lb.png', type: 'country' },
  { name: 'Macau', logo: 'https://flagcdn.com/w80/mo.png', type: 'country' },
  { name: 'Malaysia', logo: 'https://flagcdn.com/w80/my.png', type: 'country' },
  { name: 'Maldives', logo: 'https://flagcdn.com/w80/mv.png', type: 'country' },
  { name: 'Mongolia', logo: 'https://flagcdn.com/w80/mn.png', type: 'country' },
  { name: 'Myanmar', logo: 'https://flagcdn.com/w80/mm.png', type: 'country' },
  { name: 'Nepal', logo: 'https://flagcdn.com/w80/np.png', type: 'country' },
  { name: 'North Korea', logo: 'https://flagcdn.com/w80/kp.png', type: 'country' },
  { name: 'Oman', logo: 'https://flagcdn.com/w80/om.png', type: 'country' },
  { name: 'Pakistan', logo: 'https://flagcdn.com/w80/pk.png', type: 'country' },
  { name: 'Palestine', logo: 'https://flagcdn.com/w80/ps.png', type: 'country' },
  { name: 'Philippines', logo: 'https://flagcdn.com/w80/ph.png', type: 'country' },
  { name: 'Qatar', logo: 'https://flagcdn.com/w80/qa.png', type: 'country' },
  { name: 'Saudi Arabia', logo: 'https://flagcdn.com/w80/sa.png', type: 'country' },
  { name: 'Singapore', logo: 'https://flagcdn.com/w80/sg.png', type: 'country' },
  { name: 'South Korea', logo: 'https://flagcdn.com/w80/kr.png', type: 'country' },
  { name: 'Sri Lanka', logo: 'https://flagcdn.com/w80/lk.png', type: 'country' },
  { name: 'Syria', logo: 'https://flagcdn.com/w80/sy.png', type: 'country' },
  { name: 'Tajikistan', logo: 'https://flagcdn.com/w80/tj.png', type: 'country' },
  { name: 'Thailand', logo: 'https://flagcdn.com/w80/th.png', type: 'country' },
  { name: 'Timor-Leste', logo: 'https://flagcdn.com/w80/tl.png', type: 'country' },
  { name: 'Turkmenistan', logo: 'https://flagcdn.com/w80/tm.png', type: 'country' },
  { name: 'United Arab Emirates', logo: 'https://flagcdn.com/w80/ae.png', type: 'country' },
  { name: 'Uzbekistan', logo: 'https://flagcdn.com/w80/uz.png', type: 'country' },
  { name: 'Vietnam', logo: 'https://flagcdn.com/w80/vn.png', type: 'country' },
  { name: 'Yemen', logo: 'https://flagcdn.com/w80/ye.png', type: 'country' },
  // CAF (54 members)
  { name: 'Algeria', logo: 'https://flagcdn.com/w80/dz.png', type: 'country' },
  { name: 'Angola', logo: 'https://flagcdn.com/w80/ao.png', type: 'country' },
  { name: 'Benin', logo: 'https://flagcdn.com/w80/bj.png', type: 'country' },
  { name: 'Botswana', logo: 'https://flagcdn.com/w80/bw.png', type: 'country' },
  { name: 'Burkina Faso', logo: 'https://flagcdn.com/w80/bf.png', type: 'country' },
  { name: 'Burundi', logo: 'https://flagcdn.com/w80/bi.png', type: 'country' },
  { name: 'Cameroon', logo: 'https://flagcdn.com/w80/cm.png', type: 'country' },
  { name: 'Cape Verde', logo: 'https://flagcdn.com/w80/cv.png', type: 'country' },
  { name: 'Central African Republic', logo: 'https://flagcdn.com/w80/cf.png', type: 'country' },
  { name: 'Chad', logo: 'https://flagcdn.com/w80/td.png', type: 'country' },
  { name: 'Comoros', logo: 'https://flagcdn.com/w80/km.png', type: 'country' },
  { name: 'Congo', logo: 'https://flagcdn.com/w80/cg.png', type: 'country' },
  { name: 'DR Congo', logo: 'https://flagcdn.com/w80/cd.png', type: 'country' },
  { name: 'Djibouti', logo: 'https://flagcdn.com/w80/dj.png', type: 'country' },
  { name: 'Egypt', logo: 'https://flagcdn.com/w80/eg.png', type: 'country' },
  { name: 'Equatorial Guinea', logo: 'https://flagcdn.com/w80/gq.png', type: 'country' },
  { name: 'Eritrea', logo: 'https://flagcdn.com/w80/er.png', type: 'country' },
  { name: 'Eswatini', logo: 'https://flagcdn.com/w80/sz.png', type: 'country' },
  { name: 'Ethiopia', logo: 'https://flagcdn.com/w80/et.png', type: 'country' },
  { name: 'Gabon', logo: 'https://flagcdn.com/w80/ga.png', type: 'country' },
  { name: 'Gambia', logo: 'https://flagcdn.com/w80/gm.png', type: 'country' },
  { name: 'Ghana', logo: 'https://flagcdn.com/w80/gh.png', type: 'country' },
  { name: 'Guinea', logo: 'https://flagcdn.com/w80/gn.png', type: 'country' },
  { name: 'Guinea-Bissau', logo: 'https://flagcdn.com/w80/gw.png', type: 'country' },
  { name: 'Ivory Coast', logo: 'https://flagcdn.com/w80/ci.png', type: 'country' },
  { name: 'Kenya', logo: 'https://flagcdn.com/w80/ke.png', type: 'country' },
  { name: 'Lesotho', logo: 'https://flagcdn.com/w80/ls.png', type: 'country' },
  { name: 'Liberia', logo: 'https://flagcdn.com/w80/lr.png', type: 'country' },
  { name: 'Libya', logo: 'https://flagcdn.com/w80/ly.png', type: 'country' },
  { name: 'Madagascar', logo: 'https://flagcdn.com/w80/mg.png', type: 'country' },
  { name: 'Malawi', logo: 'https://flagcdn.com/w80/mw.png', type: 'country' },
  { name: 'Mali', logo: 'https://flagcdn.com/w80/ml.png', type: 'country' },
  { name: 'Mauritania', logo: 'https://flagcdn.com/w80/mr.png', type: 'country' },
  { name: 'Mauritius', logo: 'https://flagcdn.com/w80/mu.png', type: 'country' },
  { name: 'Morocco', logo: 'https://flagcdn.com/w80/ma.png', type: 'country' },
  { name: 'Mozambique', logo: 'https://flagcdn.com/w80/mz.png', type: 'country' },
  { name: 'Namibia', logo: 'https://flagcdn.com/w80/na.png', type: 'country' },
  { name: 'Niger', logo: 'https://flagcdn.com/w80/ne.png', type: 'country' },
  { name: 'Nigeria', logo: 'https://flagcdn.com/w80/ng.png', type: 'country' },
  { name: 'Rwanda', logo: 'https://flagcdn.com/w80/rw.png', type: 'country' },
  { name: 'São Tomé and Príncipe', logo: 'https://flagcdn.com/w80/st.png', type: 'country' },
  { name: 'Senegal', logo: 'https://flagcdn.com/w80/sn.png', type: 'country' },
  { name: 'Seychelles', logo: 'https://flagcdn.com/w80/sc.png', type: 'country' },
  { name: 'Sierra Leone', logo: 'https://flagcdn.com/w80/sl.png', type: 'country' },
  { name: 'Somalia', logo: 'https://flagcdn.com/w80/so.png', type: 'country' },
  { name: 'South Africa', logo: 'https://flagcdn.com/w80/za.png', type: 'country' },
  { name: 'South Sudan', logo: 'https://flagcdn.com/w80/ss.png', type: 'country' },
  { name: 'Sudan', logo: 'https://flagcdn.com/w80/sd.png', type: 'country' },
  { name: 'Tanzania', logo: 'https://flagcdn.com/w80/tz.png', type: 'country' },
  { name: 'Togo', logo: 'https://flagcdn.com/w80/tg.png', type: 'country' },
  { name: 'Tunisia', logo: 'https://flagcdn.com/w80/tn.png', type: 'country' },
  { name: 'Uganda', logo: 'https://flagcdn.com/w80/ug.png', type: 'country' },
  { name: 'Zambia', logo: 'https://flagcdn.com/w80/zm.png', type: 'country' },
  { name: 'Zimbabwe', logo: 'https://flagcdn.com/w80/zw.png', type: 'country' },
  // CONCACAF (41 members)
  { name: 'Antigua and Barbuda', logo: 'https://flagcdn.com/w80/ag.png', type: 'country' },
  { name: 'Bahamas', logo: 'https://flagcdn.com/w80/bs.png', type: 'country' },
  { name: 'Barbados', logo: 'https://flagcdn.com/w80/bb.png', type: 'country' },
  { name: 'Belize', logo: 'https://flagcdn.com/w80/bz.png', type: 'country' },
  { name: 'Canada', logo: 'https://flagcdn.com/w80/ca.png', type: 'country' },
  { name: 'Costa Rica', logo: 'https://flagcdn.com/w80/cr.png', type: 'country' },
  { name: 'Cuba', logo: 'https://flagcdn.com/w80/cu.png', type: 'country' },
  { name: 'Dominica', logo: 'https://flagcdn.com/w80/dm.png', type: 'country' },
  { name: 'Dominican Republic', logo: 'https://flagcdn.com/w80/do.png', type: 'country' },
  { name: 'El Salvador', logo: 'https://flagcdn.com/w80/sv.png', type: 'country' },
  { name: 'Grenada', logo: 'https://flagcdn.com/w80/gd.png', type: 'country' },
  { name: 'Guatemala', logo: 'https://flagcdn.com/w80/gt.png', type: 'country' },
  { name: 'Guyana', logo: 'https://flagcdn.com/w80/gy.png', type: 'country' },
  { name: 'Haiti', logo: 'https://flagcdn.com/w80/ht.png', type: 'country' },
  { name: 'Honduras', logo: 'https://flagcdn.com/w80/hn.png', type: 'country' },
  { name: 'Jamaica', logo: 'https://flagcdn.com/w80/jm.png', type: 'country' },
  { name: 'Mexico', logo: 'https://flagcdn.com/w80/mx.png', type: 'country' },
  { name: 'Nicaragua', logo: 'https://flagcdn.com/w80/ni.png', type: 'country' },
  { name: 'Panama', logo: 'https://flagcdn.com/w80/pa.png', type: 'country' },
  { name: 'Saint Kitts and Nevis', logo: 'https://flagcdn.com/w80/kn.png', type: 'country' },
  { name: 'Saint Lucia', logo: 'https://flagcdn.com/w80/lc.png', type: 'country' },
  { name: 'Saint Vincent and the Grenadines', logo: 'https://flagcdn.com/w80/vc.png', type: 'country' },
  { name: 'Suriname', logo: 'https://flagcdn.com/w80/sr.png', type: 'country' },
  { name: 'Trinidad and Tobago', logo: 'https://flagcdn.com/w80/tt.png', type: 'country' },
  { name: 'United States', logo: 'https://flagcdn.com/w80/us.png', type: 'country' },
  // CONMEBOL (10 members)
  { name: 'Argentina', logo: 'https://flagcdn.com/w80/ar.png', type: 'country' },
  { name: 'Bolivia', logo: 'https://flagcdn.com/w80/bo.png', type: 'country' },
  { name: 'Brazil', logo: 'https://flagcdn.com/w80/br.png', type: 'country' },
  { name: 'Chile', logo: 'https://flagcdn.com/w80/cl.png', type: 'country' },
  { name: 'Colombia', logo: 'https://flagcdn.com/w80/co.png', type: 'country' },
  { name: 'Ecuador', logo: 'https://flagcdn.com/w80/ec.png', type: 'country' },
  { name: 'Paraguay', logo: 'https://flagcdn.com/w80/py.png', type: 'country' },
  { name: 'Peru', logo: 'https://flagcdn.com/w80/pe.png', type: 'country' },
  { name: 'Uruguay', logo: 'https://flagcdn.com/w80/uy.png', type: 'country' },
  { name: 'Venezuela', logo: 'https://flagcdn.com/w80/ve.png', type: 'country' },
  // OFC (13 members)
  { name: 'American Samoa', logo: 'https://flagcdn.com/w80/as.png', type: 'country' },
  { name: 'Cook Islands', logo: 'https://flagcdn.com/w80/ck.png', type: 'country' },
  { name: 'Fiji', logo: 'https://flagcdn.com/w80/fj.png', type: 'country' },
  { name: 'New Caledonia', logo: 'https://flagcdn.com/w80/nc.png', type: 'country' },
  { name: 'New Zealand', logo: 'https://flagcdn.com/w80/nz.png', type: 'country' },
  { name: 'Papua New Guinea', logo: 'https://flagcdn.com/w80/pg.png', type: 'country' },
  { name: 'Samoa', logo: 'https://flagcdn.com/w80/ws.png', type: 'country' },
  { name: 'Solomon Islands', logo: 'https://flagcdn.com/w80/sb.png', type: 'country' },
  { name: 'Tahiti', logo: 'https://flagcdn.com/w80/pf.png', type: 'country' },
  { name: 'Tonga', logo: 'https://flagcdn.com/w80/to.png', type: 'country' },
  { name: 'Vanuatu', logo: 'https://flagcdn.com/w80/vu.png', type: 'country' },
  // UEFA (55 members)
  { name: 'Albania', logo: 'https://flagcdn.com/w80/al.png', type: 'country' },
  { name: 'Andorra', logo: 'https://flagcdn.com/w80/ad.png', type: 'country' },
  { name: 'Armenia', logo: 'https://flagcdn.com/w80/am.png', type: 'country' },
  { name: 'Austria', logo: 'https://flagcdn.com/w80/at.png', type: 'country' },
  { name: 'Azerbaijan', logo: 'https://flagcdn.com/w80/az.png', type: 'country' },
  { name: 'Belarus', logo: 'https://flagcdn.com/w80/by.png', type: 'country' },
  { name: 'Belgium', logo: 'https://flagcdn.com/w80/be.png', type: 'country' },
  { name: 'Bosnia and Herzegovina', logo: 'https://flagcdn.com/w80/ba.png', type: 'country' },
  { name: 'Bulgaria', logo: 'https://flagcdn.com/w80/bg.png', type: 'country' },
  { name: 'Croatia', logo: 'https://flagcdn.com/w80/hr.png', type: 'country' },
  { name: 'Cyprus', logo: 'https://flagcdn.com/w80/cy.png', type: 'country' },
  { name: 'Czech Republic', logo: 'https://flagcdn.com/w80/cz.png', type: 'country' },
  { name: 'Denmark', logo: 'https://flagcdn.com/w80/dk.png', type: 'country' },
  { name: 'England', logo: 'https://flagcdn.com/w80/gb-eng.png', type: 'country' },
  { name: 'Estonia', logo: 'https://flagcdn.com/w80/ee.png', type: 'country' },
  { name: 'Faroe Islands', logo: 'https://flagcdn.com/w80/fo.png', type: 'country' },
  { name: 'Finland', logo: 'https://flagcdn.com/w80/fi.png', type: 'country' },
  { name: 'France', logo: 'https://flagcdn.com/w80/fr.png', type: 'country' },
  { name: 'Georgia', logo: 'https://flagcdn.com/w80/ge.png', type: 'country' },
  { name: 'Germany', logo: 'https://flagcdn.com/w80/de.png', type: 'country' },
  { name: 'Gibraltar', logo: 'https://flagcdn.com/w80/gi.png', type: 'country' },
  { name: 'Greece', logo: 'https://flagcdn.com/w80/gr.png', type: 'country' },
  { name: 'Hungary', logo: 'https://flagcdn.com/w80/hu.png', type: 'country' },
  { name: 'Iceland', logo: 'https://flagcdn.com/w80/is.png', type: 'country' },
  { name: 'Israel', logo: 'https://flagcdn.com/w80/il.png', type: 'country' },
  { name: 'Italy', logo: 'https://flagcdn.com/w80/it.png', type: 'country' },
  { name: 'Kazakhstan', logo: 'https://flagcdn.com/w80/kz.png', type: 'country' },
  { name: 'Kosovo', logo: 'https://flagcdn.com/w80/xk.png', type: 'country' },
  { name: 'Latvia', logo: 'https://flagcdn.com/w80/lv.png', type: 'country' },
  { name: 'Liechtenstein', logo: 'https://flagcdn.com/w80/li.png', type: 'country' },
  { name: 'Lithuania', logo: 'https://flagcdn.com/w80/lt.png', type: 'country' },
  { name: 'Luxembourg', logo: 'https://flagcdn.com/w80/lu.png', type: 'country' },
  { name: 'Malta', logo: 'https://flagcdn.com/w80/mt.png', type: 'country' },
  { name: 'Moldova', logo: 'https://flagcdn.com/w80/md.png', type: 'country' },
  { name: 'Monaco', logo: 'https://flagcdn.com/w80/mc.png', type: 'country' },
  { name: 'Montenegro', logo: 'https://flagcdn.com/w80/me.png', type: 'country' },
  { name: 'Netherlands', logo: 'https://flagcdn.com/w80/nl.png', type: 'country' },
  { name: 'North Macedonia', logo: 'https://flagcdn.com/w80/mk.png', type: 'country' },
  { name: 'Northern Ireland', logo: 'https://flagcdn.com/w80/gb-nir.png', type: 'country' },
  { name: 'Norway', logo: 'https://flagcdn.com/w80/no.png', type: 'country' },
  { name: 'Poland', logo: 'https://flagcdn.com/w80/pl.png', type: 'country' },
  { name: 'Portugal', logo: 'https://flagcdn.com/w80/pt.png', type: 'country' },
  { name: 'Republic of Ireland', logo: 'https://flagcdn.com/w80/ie.png', type: 'country' },
  { name: 'Romania', logo: 'https://flagcdn.com/w80/ro.png', type: 'country' },
  { name: 'Russia', logo: 'https://flagcdn.com/w80/ru.png', type: 'country' },
  { name: 'San Marino', logo: 'https://flagcdn.com/w80/sm.png', type: 'country' },
  { name: 'Scotland', logo: 'https://flagcdn.com/w80/gb-sct.png', type: 'country' },
  { name: 'Serbia', logo: 'https://flagcdn.com/w80/rs.png', type: 'country' },
  { name: 'Slovakia', logo: 'https://flagcdn.com/w80/sk.png', type: 'country' },
  { name: 'Slovenia', logo: 'https://flagcdn.com/w80/si.png', type: 'country' },
  { name: 'Spain', logo: 'https://flagcdn.com/w80/es.png', type: 'country' },
  { name: 'Sweden', logo: 'https://flagcdn.com/w80/se.png', type: 'country' },
  { name: 'Switzerland', logo: 'https://flagcdn.com/w80/ch.png', type: 'country' },
  { name: 'Turkey', logo: 'https://flagcdn.com/w80/tr.png', type: 'country' },
  { name: 'Ukraine', logo: 'https://flagcdn.com/w80/ua.png', type: 'country' },
  { name: 'Wales', logo: 'https://flagcdn.com/w80/gb-wls.png', type: 'country' },
]

// ─── Popular Football Clubs with Logo URLs ───
export const footballClubs: TeamEntry[] = [
  // Premier League
  { name: 'Manchester City', logo: 'https://upload.wikimedia.org/wikipedia/en/e/eb/Manchester_City_FC_badge.svg', type: 'club' },
  { name: 'Liverpool', logo: 'https://upload.wikimedia.org/wikipedia/en/0/0c/Liverpool_FC.svg', type: 'club' },
  { name: 'Arsenal', logo: 'https://upload.wikimedia.org/wikipedia/en/5/53/Arsenal_FC.svg', type: 'club' },
  { name: 'Chelsea', logo: 'https://upload.wikimedia.org/wikipedia/en/c/cc/Chelsea_FC.svg', type: 'club' },
  { name: 'Manchester United', logo: 'https://upload.wikimedia.org/wikipedia/en/7/7a/Manchester_United_FC_crest.svg', type: 'club' },
  { name: 'Tottenham Hotspur', logo: 'https://upload.wikimedia.org/wikipedia/en/b/b4/Tottenham_Hotspur.svg', type: 'club' },
  { name: 'Newcastle United', logo: 'https://upload.wikimedia.org/wikipedia/en/5/56/Newcastle_United_Logo.svg', type: 'club' },
  { name: 'Aston Villa', logo: 'https://upload.wikimedia.org/wikipedia/en/9/9a/Aston_Villa_FC_new_crest.svg', type: 'club' },
  { name: 'Brighton', logo: 'https://upload.wikimedia.org/wikipedia/en/f/fd/Brighton_%26_Hove_Albion_logo.svg', type: 'club' },
  { name: 'West Ham', logo: 'https://upload.wikimedia.org/wikipedia/en/c/c2/West_Ham_United_FC.svg', type: 'club' },
  { name: 'Crystal Palace', logo: 'https://upload.wikimedia.org/wikipedia/en/a/a2/Crystal_Palace_FC_logo.svg', type: 'club' },
  { name: 'Everton', logo: 'https://upload.wikimedia.org/wikipedia/en/7/7c/Everton_FC_logo.svg', type: 'club' },
  { name: 'Fulham', logo: 'https://upload.wikimedia.org/wikipedia/en/e/eb/Fulham_FC.svg', type: 'club' },
  { name: 'Wolves', logo: 'https://upload.wikimedia.org/wikipedia/en/f/fc/Wolverhampton_Wanderers_logo.svg', type: 'club' },
  { name: 'Bournemouth', logo: 'https://upload.wikimedia.org/wikipedia/en/e/e5/AFC_Bournemouth.svg', type: 'club' },
  { name: 'Nottingham Forest', logo: 'https://upload.wikimedia.org/wikipedia/en/e/e7/Nottingham_Forest_F.C._logo.svg', type: 'club' },
  { name: 'Brentford', logo: 'https://upload.wikimedia.org/wikipedia/en/2/2a/Brentford_FC_crest.svg', type: 'club' },
  { name: 'Leicester City', logo: 'https://upload.wikimedia.org/wikipedia/en/2/2d/Leicester_City_crest.svg', type: 'club' },
  { name: 'Ipswich Town', logo: 'https://upload.wikimedia.org/wikipedia/en/4/47/Ipswich_Town.svg', type: 'club' },
  { name: 'Southampton', logo: 'https://upload.wikimedia.org/wikipedia/en/c/c9/Southampton_FC.svg', type: 'club' },
  // La Liga
  { name: 'Real Madrid', logo: 'https://upload.wikimedia.org/wikipedia/en/5/56/Real_Madrid_CF.svg', type: 'club' },
  { name: 'Barcelona', logo: 'https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%28crest%29.svg', type: 'club' },
  { name: 'Atlético Madrid', logo: 'https://upload.wikimedia.org/wikipedia/en/f/f9/Club_Atl%C3%A9tico_de_Madrid_Badge.svg', type: 'club' },
  { name: 'Real Sociedad', logo: 'https://upload.wikimedia.org/wikipedia/en/6/65/Real_Sociedad.svg', type: 'club' },
  { name: 'Real Betis', logo: 'https://upload.wikimedia.org/wikipedia/en/3/36/Real_Betis_Balonpie.svg', type: 'club' },
  { name: 'Sevilla', logo: 'https://upload.wikimedia.org/wikipedia/en/3/3b/Sevilla_FC_logo.svg', type: 'club' },
  { name: 'Villarreal', logo: 'https://upload.wikimedia.org/wikipedia/en/b/b1/Villarreal_CF_logo.svg', type: 'club' },
  { name: 'Athletic Bilbao', logo: 'https://upload.wikimedia.org/wikipedia/en/9/98/Athletic_Club_Bilbao.svg', type: 'club' },
  { name: 'Valencia', logo: 'https://upload.wikimedia.org/wikipedia/en/0/0a/Valencia_CF.svg', type: 'club' },
  // Serie A
  { name: 'Inter Milan', logo: 'https://upload.wikimedia.org/wikipedia/commons/0/05/FC_Internazionale_Milano_2021.svg', type: 'club' },
  { name: 'AC Milan', logo: 'https://upload.wikimedia.org/wikipedia/commons/d/d0/Logo_of_AC_Milan.svg', type: 'club' },
  { name: 'Juventus', logo: 'https://upload.wikimedia.org/wikipedia/en/b/bc/Juventus_FC_2017_logo.svg', type: 'club' },
  { name: 'Napoli', logo: 'https://upload.wikimedia.org/wikipedia/commons/2/2d/SSC_Napoli.svg', type: 'club' },
  { name: 'AS Roma', logo: 'https://upload.wikimedia.org/wikipedia/en/f/f7/AS_Roma_logo.svg', type: 'club' },
  { name: 'Lazio', logo: 'https://upload.wikimedia.org/wikipedia/en/2/21/SS_Lazio_badge.svg', type: 'club' },
  { name: 'Atalanta', logo: 'https://upload.wikimedia.org/wikipedia/en/6/6b/Atalanta_B.C._logo.svg', type: 'club' },
  { name: 'Fiorentina', logo: 'https://upload.wikimedia.org/wikipedia/en/7/74/Fiorentina_logo.svg', type: 'club' },
  // Bundesliga
  { name: 'Bayern Munich', logo: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/FC_Bayern_M%C3%BCnchen_logo_%282017%29.svg', type: 'club' },
  { name: 'Borussia Dortmund', logo: 'https://upload.wikimedia.org/wikipedia/commons/6/67/Borussia_Dortmund_logo.svg', type: 'club' },
  { name: 'RB Leipzig', logo: 'https://upload.wikimedia.org/wikipedia/en/0/04/RB_Leipzig_2014_logo.svg', type: 'club' },
  { name: 'Bayer Leverkusen', logo: 'https://upload.wikimedia.org/wikipedia/en/5/59/Bayer_04_Leverkusen_logo.svg', type: 'club' },
  { name: 'VfB Stuttgart', logo: 'https://upload.wikimedia.org/wikipedia/en/e/eb/VfB_Stuttgart_1893_logo.svg', type: 'club' },
  { name: 'Eintracht Frankfurt', logo: 'https://upload.wikimedia.org/wikipedia/en/e/e5/Eintracht_Frankfurt_logo.svg', type: 'club' },
  { name: 'SC Freiburg', logo: 'https://upload.wikimedia.org/wikipedia/en/4/44/SC_Freiburg_logo.svg', type: 'club' },
  { name: 'Wolfsburg', logo: 'https://upload.wikimedia.org/wikipedia/en/7/76/VfL_Wolfsburg_Logo.svg', type: 'club' },
  { name: 'Borussia Mönchengladbach', logo: 'https://upload.wikimedia.org/wikipedia/en/b/b4/Borussia_M%C3%B6nchengladbach_logo.svg', type: 'club' },
  // Ligue 1
  { name: 'PSG', logo: 'https://upload.wikimedia.org/wikipedia/en/a/a7/Paris_Saint-Germain_F.C..svg', type: 'club' },
  { name: 'Marseille', logo: 'https://upload.wikimedia.org/wikipedia/en/3/3c/Olympique_de_Marseille_logo.svg', type: 'club' },
  { name: 'Monaco', logo: 'https://upload.wikimedia.org/wikipedia/en/8/83/AS_Monaco_FC_logo.svg', type: 'club' },
  { name: 'Lyon', logo: 'https://upload.wikimedia.org/wikipedia/en/4/41/Olympique_Lyonnais_logo.svg', type: 'club' },
  { name: 'Lille', logo: 'https://upload.wikimedia.org/wikipedia/en/3/33/LOSC_Lille_logo.svg', type: 'club' },
  { name: 'Nice', logo: 'https://upload.wikimedia.org/wikipedia/en/8/85/OGC_Nice_logo.svg', type: 'club' },
  { name: 'Lens', logo: 'https://upload.wikimedia.org/wikipedia/en/4/41/RC_Lens_logo.svg', type: 'club' },
  // Eredivisie
  { name: 'Ajax', logo: 'https://upload.wikimedia.org/wikipedia/en/7/72/Ajax_Amsterdam_logo.svg', type: 'club' },
  { name: 'PSV', logo: 'https://upload.wikimedia.org/wikipedia/en/3/3d/PSV_Eindhoven_logo.svg', type: 'club' },
  { name: 'Feyenoord', logo: 'https://upload.wikimedia.org/wikipedia/en/4/44/Feyenoord_logo.svg', type: 'club' },
  // Primeira Liga
  { name: 'Benfica', logo: 'https://upload.wikimedia.org/wikipedia/en/a/a2/SL_Benfica_logo.svg', type: 'club' },
  { name: 'Porto', logo: 'https://upload.wikimedia.org/wikipedia/en/3/3b/FC_Porto.svg', type: 'club' },
  { name: 'Sporting CP', logo: 'https://upload.wikimedia.org/wikipedia/en/f/f5/Sporting_Clube_de_Portugal.svg', type: 'club' },
  // Other notable clubs
  { name: 'Celtic', logo: 'https://upload.wikimedia.org/wikipedia/en/3/3b/Celtic_FC.svg', type: 'club' },
  { name: 'Rangers', logo: 'https://upload.wikimedia.org/wikipedia/en/e/e2/Rangers_FC.svg', type: 'club' },
  { name: 'Galatasaray', logo: 'https://upload.wikimedia.org/wikipedia/en/b/b4/Galatasaray_Sports_Club_Logo.svg', type: 'club' },
  { name: 'Fenerbahçe', logo: 'https://upload.wikimedia.org/wikipedia/en/e/ed/Fenerbah%C3%A7e_SK.svg', type: 'club' },
  { name: 'Besiktas', logo: 'https://upload.wikimedia.org/wikipedia/en/1/1f/Besiktas_JK_Logo.svg', type: 'club' },
  { name: 'Al Hilal', logo: 'https://upload.wikimedia.org/wikipedia/en/e/e3/Al_Hilal_FC.svg', type: 'club' },
  { name: 'Al Nassr', logo: 'https://upload.wikimedia.org/wikipedia/en/a/a2/Al_Nassr_FC.svg', type: 'club' },
  { name: 'Al Ahli', logo: 'https://upload.wikimedia.org/wikipedia/en/1/1a/Al-Ahli_Saudi_FC.svg', type: 'club' },
  { name: 'Al Ittihad', logo: 'https://upload.wikimedia.org/wikipedia/en/b/bc/Al-Ittihad_Club.svg', type: 'club' },
  // MLS
  { name: 'Inter Miami', logo: 'https://upload.wikimedia.org/wikipedia/en/0/0d/Inter_Miami_CF_logo.svg', type: 'club' },
  { name: 'LA Galaxy', logo: 'https://upload.wikimedia.org/wikipedia/en/b/b9/LA_Galaxy_logo.svg', type: 'club' },
  { name: 'New York City FC', logo: 'https://upload.wikimedia.org/wikipedia/en/7/76/New_York_City_FC.svg', type: 'club' },
  // Argentine clubs
  { name: 'River Plate', logo: 'https://upload.wikimedia.org/wikipedia/en/3/3d/Club_Atl%C3%A9tico_River_Plate_logo.svg', type: 'club' },
  { name: 'Boca Juniors', logo: 'https://upload.wikimedia.org/wikipedia/en/7/73/Boca_Juniors_logo.svg', type: 'club' },
]

// ─── ICC Member Countries (Full Members + Associates) ───
export const iccCountries: TeamEntry[] = [
  // Full Members (12)
  { name: 'Australia', logo: 'https://flagcdn.com/w80/au.png', type: 'country' },
  { name: 'England', logo: 'https://flagcdn.com/w80/gb-eng.png', type: 'country' },
  { name: 'India', logo: 'https://flagcdn.com/w80/in.png', type: 'country' },
  { name: 'New Zealand', logo: 'https://flagcdn.com/w80/nz.png', type: 'country' },
  { name: 'Pakistan', logo: 'https://flagcdn.com/w80/pk.png', type: 'country' },
  { name: 'South Africa', logo: 'https://flagcdn.com/w80/za.png', type: 'country' },
  { name: 'Sri Lanka', logo: 'https://flagcdn.com/w80/lk.png', type: 'country' },
  { name: 'West Indies', logo: 'https://ssl.gstatic.com/onebox/media/sports/logos/optimized/qziJXGzGxNQbkPJRfxodgA_96x96.png', type: 'country' },
  { name: 'Bangladesh', logo: 'https://flagcdn.com/w80/bd.png', type: 'country' },
  { name: 'Zimbabwe', logo: 'https://flagcdn.com/w80/zw.png', type: 'country' },
  { name: 'Ireland', logo: 'https://flagcdn.com/w80/ie.png', type: 'country' },
  { name: 'Afghanistan', logo: 'https://flagcdn.com/w80/af.png', type: 'country' },
  // Associate Members
  { name: 'Netherlands', logo: 'https://flagcdn.com/w80/nl.png', type: 'country' },
  { name: 'Scotland', logo: 'https://flagcdn.com/w80/gb-sct.png', type: 'country' },
  { name: 'Nepal', logo: 'https://flagcdn.com/w80/np.png', type: 'country' },
  { name: 'Namibia', logo: 'https://flagcdn.com/w80/na.png', type: 'country' },
  { name: 'Oman', logo: 'https://flagcdn.com/w80/om.png', type: 'country' },
  { name: 'UAE', logo: 'https://flagcdn.com/w80/ae.png', type: 'country' },
  { name: 'USA', logo: 'https://flagcdn.com/w80/us.png', type: 'country' },
  { name: 'Canada', logo: 'https://flagcdn.com/w80/ca.png', type: 'country' },
  { name: 'Bermuda', logo: 'https://flagcdn.com/w80/bm.png', type: 'country' },
  { name: 'Kenya', logo: 'https://flagcdn.com/w80/ke.png', type: 'country' },
  { name: 'Uganda', logo: 'https://flagcdn.com/w80/ug.png', type: 'country' },
  { name: 'Italy', logo: 'https://flagcdn.com/w80/it.png', type: 'country' },
  { name: 'Denmark', logo: 'https://flagcdn.com/w80/dk.png', type: 'country' },
  { name: 'Guernsey', logo: 'https://flagcdn.com/w80/gg.png', type: 'country' },
  { name: 'Jersey', logo: 'https://flagcdn.com/w80/je.png', type: 'country' },
  { name: 'Malaysia', logo: 'https://flagcdn.com/w80/my.png', type: 'country' },
  { name: 'Singapore', logo: 'https://flagcdn.com/w80/sg.png', type: 'country' },
  { name: 'Papua New Guinea', logo: 'https://flagcdn.com/w80/pg.png', type: 'country' },
  { name: 'Qatar', logo: 'https://flagcdn.com/w80/qa.png', type: 'country' },
  { name: 'Saudi Arabia', logo: 'https://flagcdn.com/w80/sa.png', type: 'country' },
  { name: 'Bahrain', logo: 'https://flagcdn.com/w80/bh.png', type: 'country' },
  { name: 'Kuwait', logo: 'https://flagcdn.com/w80/kw.png', type: 'country' },
  { name: 'Thailand', logo: 'https://flagcdn.com/w80/th.png', type: 'country' },
  { name: 'Zambia', logo: 'https://flagcdn.com/w80/zm.png', type: 'country' },
  { name: 'Nigeria', logo: 'https://flagcdn.com/w80/ng.png', type: 'country' },
  { name: 'Tanzania', logo: 'https://flagcdn.com/w80/tz.png', type: 'country' },
  { name: 'Vanuatu', logo: 'https://flagcdn.com/w80/vu.png', type: 'country' },
  { name: 'Maldives', logo: 'https://flagcdn.com/w80/mv.png', type: 'country' },
  { name: 'Botswana', logo: 'https://flagcdn.com/w80/bw.png', type: 'country' },
]

/**
 * Get teams filtered by sport type
 */
export function getTeamsForSport(sport: string): TeamEntry[] {
  if (sport === 'football') {
    return [...footballClubs, ...fifaCountries]
  }
  if (sport === 'cricket') {
    return iccCountries
  }
  return fifaCountries
}

/**
 * Search teams by name (case-insensitive, partial match)
 * Priority: 1) name starts with query, 2) clubs before countries, 3) contains query
 */
export function searchTeams(query: string, sport: string, limit = 8): TeamEntry[] {
  const teams = getTeamsForSport(sport)
  if (!query.trim()) return teams.slice(0, limit)
  const q = query.toLowerCase()

  const startsWith = teams.filter(t => t.name.toLowerCase().startsWith(q))
  const contains = teams.filter(t => !t.name.toLowerCase().startsWith(q) && t.name.toLowerCase().includes(q))

  // Sort each group: clubs first, then countries
  const sortFn = (a: TeamEntry, b: TeamEntry) => {
    if (a.type === 'club' && b.type !== 'club') return -1
    if (a.type !== 'club' && b.type === 'club') return 1
    return 0
  }

  return [...startsWith.sort(sortFn), ...contains.sort(sortFn)].slice(0, limit)
}
